// Auto-generated from Mods/*.modcomponent — do not edit by hand.
// Regenerate via gen_moddb.py (see HANDOFF).
using System.Collections.Generic;

namespace TldHacks;

internal static class ItemDatabaseMod
{
    public static readonly List<ItemEntry> All = new List<ItemEntry>
    {
    new ItemEntry("GEAR_Battery9V", "工业电池 [Toolbox]", "材料", "", 0.05f),
    new ItemEntry("GEAR_Bones", "碎骨片 [Toolbox]", "材料", "", 0.1f),
    new ItemEntry("GEAR_CeramicShards", "黏土碎片 [Toolbox]", "材料", "", 0.05f),
    new ItemEntry("GEAR_CrumpledPaper", "废纸 [Toolbox]", "材料", "", 0.01f),
    new ItemEntry("GEAR_ElectronicParts", "电子零件 [Toolbox]", "材料", "", 0.1f),
    new ItemEntry("GEAR_Flint", "燧石 [Toolbox]", "材料", "", 0.1f),
    new ItemEntry("GEAR_GlassShards", "玻璃碎片 [Toolbox]", "材料", "", 0.2f),
    new ItemEntry("GEAR_GunParts", "枪械部件 [Toolbox]", "材料", "", 0.5f),
    new ItemEntry("GEAR_MetalBoxForge", "金属盒 [Toolbox]", "材料", "", 2f),
    new ItemEntry("GEAR_NutsNBolts", "螺栓螺母 [Toolbox]", "材料", "", 0.05f),
    new ItemEntry("GEAR_NutsNBoltsBox", "螺栓螺母(盒) [Toolbox]", "材料", "", 0.2f),
    new ItemEntry("GEAR_RecycledGlass", "玻璃板材 [Toolbox]", "材料", "", 0.2f),
    new ItemEntry("GEAR_RecycledPlastic", "塑料板材 [Toolbox]", "材料", "", 0.4f),
    new ItemEntry("GEAR_RifleBroken", "损毁的猎枪 [Toolbox]", "材料", "", 3.8f),
    new ItemEntry("GEAR_Rock", "岩石 [Toolbox]", "材料", "", 0.2f),
    new ItemEntry("GEAR_ScrapPlastic", "废塑料 [Toolbox]", "材料", "", 0.1f),
    new ItemEntry("GEAR_StringBundle", "线团 [Toolbox]", "材料", "", 0.05f),
    new ItemEntry("GEAR_StringDurable", "耐用线材 [Toolbox]", "材料", "", 0.2f),
    new ItemEntry("GEAR_TapeRoll", "胶带 [Toolbox]", "工具", "", 0.1f),
    new ItemEntry("GEAR_TarpSheet", "防水布 [Toolbox]", "材料", "", 0.3f),
    new ItemEntry("GEAR_ARC_log", "施工原木 [Arch]", "材料", "", 6f),
    new ItemEntry("GEAR_ARC_logbundle", "一捆原木 [Arch]", "材料", "", 12f),
    new ItemEntry("GEAR_ARC_nailbox", "一盒钉子 [Arch]", "材料", "", 1.5f),
    new ItemEntry("GEAR_ARC_nails", "一把钉子 [Arch]", "材料", "", 0.1f),
    new ItemEntry("GEAR_ARC_plank", "施工木板 [Arch]", "材料", "", 2f),
    new ItemEntry("GEAR_ARC_plankbundle", "一捆木板 [Arch]", "材料", "", 10f),
    new ItemEntry("GEAR_1FirConeFuel", "冷杉果(外壳) [BF]", "材料", "", 0.1f),
    new ItemEntry("GEAR_1FirSeedBunchRoasted", "烤种子(堆叠) [BF]", "食物", "", 0.05f, 250),
    new ItemEntry("GEAR_2FirConeSeedsRoasted", "烤种子 [BF]", "食物", "", 0.01f, 50),
    new ItemEntry("GEAR_4FirCone", "冷杉果 [BF]", "材料", "", 0.12f),
    new ItemEntry("GEAR_BeeHarvestedHoney", "蜂蜜 [BF]", "食物", "", 0.5f, 800),
    new ItemEntry("GEAR_BeeHive", "蜂巢 [BF]", "材料", "", 1f),
    new ItemEntry("GEAR_BirdEggBoiled", "水煮鸟蛋 [BF]", "食物", "", 0.1f, 200),
    new ItemEntry("GEAR_BirdEggRaw", "鸟蛋 [BF]", "食物", "", 0.05f, 100),
    new ItemEntry("GEAR_BirdFeatherBundle", "乌鸦羽毛 [BF]", "材料", "", 0.2f),
    new ItemEntry("GEAR_BirdMeatCooked", "烤乌鸦肉 [BF]", "食物", "", 0.3f, 150),
    new ItemEntry("GEAR_BirdMeatRaw", "乌鸦肉 [BF]", "食物", "", 0.3f, 150),
    new ItemEntry("GEAR_CoalChunk", "煤块 [BF]", "材料", "", 0.5f),
    new ItemEntry("GEAR_CookedForagerOmelette", "觅食者煎蛋饼 [BF]", "食物", "", 0.2f, 450),
    new ItemEntry("GEAR_CookedForagerStew", "觅食者炖菜 [BF]", "食物", "", 0.4f, 1800),
    new ItemEntry("GEAR_CookedOmelette", "煎蛋饼 [BF]", "食物", "", 0.15f, 350),
    new ItemEntry("GEAR_CookedSpanishOmelette", "土豆煎蛋饼 [BF]", "食物", "", 0.35f, 650),
    new ItemEntry("GEAR_CrushedHalite", "石盐末 [BF]", "材料", "", 0.1f),
    new ItemEntry("GEAR_CryptidHeadWear", "M-幽林头饰 [BF]", "衣物", "", 2.2f),
    new ItemEntry("GEAR_CuredFishBassLarge", "大嘴鲈鱼肉干 [BF]", "食物", "", 8f, 2300),
    new ItemEntry("GEAR_CuredFishBassSmall", "小嘴鲈鱼肉干 [BF]", "食物", "", 5f, 1500),
    new ItemEntry("GEAR_CuredFishBurbot", "鳕鱼肉干 [BF]", "食物", "", 6f, 1950),
    new ItemEntry("GEAR_CuredFishGoldeye", "金目鱼肉干 [BF]", "食物", "", 2.1f, 630),
    new ItemEntry("GEAR_CuredFishRed", "王鱼肉干 [BF]", "食物", "", 3.1f, 930),
    new ItemEntry("GEAR_CuredFishRock", "岩鱼肉干 [BF]", "食物", "", 5f, 1500),
    new ItemEntry("GEAR_CuredFishSalmon", "大马哈鱼肉干 [BF]", "食物", "", 5.5f, 1650),
    new ItemEntry("GEAR_CuredFishTrout", "虹鳟鱼肉干 [BF]", "食物", "", 2.3f, 575),
    new ItemEntry("GEAR_CuredFishWhite", "湖白鲑肉干 [BF]", "食物", "", 2.3f, 575),
    new ItemEntry("GEAR_CuredMeatBear", "熊肉干 [BF]", "食物", "", 1f, 900),
    new ItemEntry("GEAR_CuredMeatBird", "乌鸦肉干 [BF]", "食物", "", 0.3f, 150),
    new ItemEntry("GEAR_CuredMeatMoose", "驼鹿肉干 [BF]", "食物", "", 1f, 900),
    new ItemEntry("GEAR_CuredMeatOrca", "鲸鱼肉干 [BF]", "食物", "", 1f, 1000),
    new ItemEntry("GEAR_CuredMeatPtarmigan", "鸡肉干 [BF]", "食物", "", 1f, 500),
    new ItemEntry("GEAR_CuredMeatRabbit", "兔肉干 [BF]", "食物", "", 1f, 450),
    new ItemEntry("GEAR_CuredMeatVenison", "鹿肉干 [BF]", "食物", "", 1f, 800),
    new ItemEntry("GEAR_CuredMeatWolf", "狼肉干 [BF]", "食物", "", 1f, 700),
    new ItemEntry("GEAR_FuelOrca", "鲸油 [BF]", "材料", "", 0.1f),
    new ItemEntry("GEAR_GreyWolfPelt", "M-森林狼皮 [BF]", "材料", "", 1f),
    new ItemEntry("GEAR_GreyWolfPeltDried", "M-森林狼皮 [BF]", "材料", "", 1f),
    new ItemEntry("GEAR_GreyWolfSkinBraces", "M-森林狼护臂 [BF]", "衣物", "", 1.5f),
    new ItemEntry("GEAR_GreyWolfSkinCoat", "M-森兰狼大衣 [BF]", "衣物", "", 4.5f),
    new ItemEntry("GEAR_Halite", "石盐(大) [BF]", "材料", "", 0.5f),
    new ItemEntry("GEAR_HaliteSmall", "石盐(小) [BF]", "材料", "", 0.1f),
    new ItemEntry("GEAR_Largemouthbass", "largemouthbass [BF]", "食物", "", 8f, 2300),
    new ItemEntry("GEAR_NestEmpty", "空巢穴 [BF]", "材料", "", 0.2f),
    new ItemEntry("GEAR_NestFull1", "鸟巢 [BF]", "材料", "", 0.25f),
    new ItemEntry("GEAR_NestFull2", "鸟巢 [BF]", "材料", "", 0.3f),
    new ItemEntry("GEAR_NestFull3", "鸟巢 [BF]", "材料", "", 0.35f),
    new ItemEntry("GEAR_OrcaBones1", "虎鲸骸骨 [BF]", "材料", "", 1f),
    new ItemEntry("GEAR_OrcaBones2", "虎鲸骸骨 [BF]", "材料", "", 1f),
    new ItemEntry("GEAR_OrcaFat", "虎鲸脂肪 [BF]", "其他", "", 2f),
    new ItemEntry("GEAR_OrcaMeatCooked", "熟鲸鱼肉 [BF]", "食物", "", 1f, 1000),
    new ItemEntry("GEAR_OrcaMeatRaw", "生鲸鱼肉 [BF]", "食物", "", 1f, 1000),
    new ItemEntry("GEAR_SaltedFishBassLarge", "腌制的大嘴鲈鱼 [BF]", "食物", "", 8f, 2300),
    new ItemEntry("GEAR_SaltedFishBassSmall", "腌制的小嘴鲈鱼 [BF]", "食物", "", 5f, 1500),
    new ItemEntry("GEAR_SaltedFishBurbot", "腌制的鳕鱼 [BF]", "食物", "", 6f, 1950),
    new ItemEntry("GEAR_SaltedFishGoldeye", "腌制的金目鱼 [BF]", "食物", "", 2.1f, 630),
    new ItemEntry("GEAR_SaltedFishRed", "腌制的王鱼 [BF]", "食物", "", 3.1f, 930),
    new ItemEntry("GEAR_SaltedFishRock", "腌制的岩鱼 [BF]", "食物", "", 5f, 1500),
    new ItemEntry("GEAR_SaltedFishSalmon", "腌制的大马哈鱼 [BF]", "食物", "", 5.5f, 1650),
    new ItemEntry("GEAR_SaltedFishTrout", "腌制的虹鳟鱼 [BF]", "食物", "", 2.3f, 575),
    new ItemEntry("GEAR_SaltedFishWhite", "腌制的湖白鲑 [BF]", "食物", "", 2.3f, 575),
    new ItemEntry("GEAR_SaltedMeatBear", "腌制的熊肉 [BF]", "食物", "", 1f, 900),
    new ItemEntry("GEAR_SaltedMeatBird", "腌制的乌鸦肉 [BF]", "食物", "", 0.3f, 150),
    new ItemEntry("GEAR_SaltedMeatMoose", "腌制的驼鹿肉 [BF]", "食物", "", 1f, 900),
    new ItemEntry("GEAR_SaltedMeatOrca", "腌制的鲸鱼肉 [BF]", "食物", "", 1f, 1000),
    new ItemEntry("GEAR_SaltedMeatPtarmigan", "腌制的鸡肉 [BF]", "食物", "", 1f, 500),
    new ItemEntry("GEAR_SaltedMeatRabbit", "腌制的兔子肉 [BF]", "食物", "", 1f, 500),
    new ItemEntry("GEAR_SaltedMeatVenison", "腌制的鹿肉 [BF]", "食物", "", 1f, 900),
    new ItemEntry("GEAR_SaltedMeatWolf", "腌制的狼肉 [BF]", "食物", "", 1f, 800),
    new ItemEntry("GEAR_SkullBear", "熊头骨 [BF]", "材料", "", 5f),
    new ItemEntry("GEAR_SkullStag", "鹿头骨 [BF]", "材料", "", 3.5f),
    new ItemEntry("GEAR_UncookedForagerOmelette", "打好的蛋液 [BF]", "食物", "", 0.2f, 200),
    new ItemEntry("GEAR_UncookedForagerStew", "觅食者炖菜 [BF]", "食物", "", 0.4f, 700),
    new ItemEntry("GEAR_UncookedOmelette", "打好的蛋液 [BF]", "食物", "", 0.15f, 200),
    new ItemEntry("GEAR_UncookedSpanishOmelette", "打好的蛋液 [BF]", "食物", "", 0.15f, 300),
    new ItemEntry("GEAR_MapBI", "荒凉水湾地图 [Camp]", "工具", "", 0.1f),
    new ItemEntry("GEAR_MapBIDeco", "荒凉水湾地图 [Camp]", "工具", "", 0.1f),
    new ItemEntry("GEAR_MapCH", "沿海公路地图 [Camp]", "工具", "", 0.1f),
    new ItemEntry("GEAR_MapCHDeco", "沿海公路地图 [Camp]", "工具", "", 0.1f),
    new ItemEntry("GEAR_MapML", "大熊岛地理杂志 [Camp]", "工具", "", 0.1f),
    new ItemEntry("GEAR_MapMLDeco", "大熊岛地理杂志 [Camp]", "工具", "", 0.1f),
    new ItemEntry("GEAR_MapMT", "米尔顿地图 [Camp]", "工具", "", 0.1f),
    new ItemEntry("GEAR_MapMTDeco", "米尔顿地图 [Camp]", "工具", "", 0.1f),
    new ItemEntry("GEAR_MapPV", "怡人山谷地图 [Camp]", "工具", "", 0.1f),
    new ItemEntry("GEAR_MapPVDeco", "怡人山谷地图 [Camp]", "工具", "", 0.1f),
    new ItemEntry("GEAR_MetalLighter", "C-防风打火机(自改) [Camp]", "材料", "", 0.1f),
    new ItemEntry("GEAR_SatchelM", "C-巡游者背包(自改) [Camp]", "衣物", "", 1.5f),
    new ItemEntry("GEAR_TanningRack", "C-鞣制架 [Camp]", "工具", "", 1f),
    new ItemEntry("GEAR_TanningRackBP1", "C-鞣制架 [Camp]", "工具", "", 2f),
    new ItemEntry("GEAR_TanningRackBP2", "C-鞣制架 [Camp]", "工具", "", 2f),
    new ItemEntry("GEAR_TanningRackDPS1", "C-鞣制架 [Camp]", "工具", "", 1.5f),
    new ItemEntry("GEAR_TanningRackDPS2", "C-鞣制架 [Camp]", "工具", "", 1.5f),
    new ItemEntry("GEAR_TanningRackMP1", "C-鞣制架 [Camp]", "工具", "", 6f),
    new ItemEntry("GEAR_TanningRackMP2", "C-鞣制架 [Camp]", "工具", "", 6f),
    new ItemEntry("GEAR_TanningRackWPS1", "C-鞣制架 [Camp]", "工具", "", 1.75f),
    new ItemEntry("GEAR_TanningRackWPS2", "C-鞣制架 [Camp]", "工具", "", 1.75f),
    new ItemEntry("GEAR_Tent", "C-防水帐篷 [Camp]", "工具", "", 2f),
    new ItemEntry("GEAR_TentBear", "C-猎人帐篷(自改) [Camp]", "工具", "", 6f),
    new ItemEntry("GEAR_CargoToolbelt", "工装裤(腰带) [CE]", "其他", "", 0.95f),
    new ItemEntry("GEAR_ChemicalICrampons", "防化靴(简易鞋底钉) [CE]", "其他", "", 2.75f),
    new ItemEntry("GEAR_ChemicalNCrampons", "防化靴(鞋底钉) [CE]", "其他", "", 2.5f),
    new ItemEntry("GEAR_CombatICrampons", "军靴(简易鞋底钉) [CE]", "其他", "", 2.75f),
    new ItemEntry("GEAR_CombatNCrampons", "军靴(鞋底钉) [CE]", "其他", "", 2.5f),
    new ItemEntry("GEAR_CombatToolbelt", "作战裤(腰带) [CE]", "其他", "", 0.95f),
    new ItemEntry("GEAR_DeerskinICrampons", "鹿皮靴(简易鞋底钉) [CE]", "其他", "", 2.75f),
    new ItemEntry("GEAR_DeerskinNCrampons", "鹿皮靴(鞋底钉) [CE]", "其他", "", 2.5f),
    new ItemEntry("GEAR_DeerskinToolbelt", "鹿皮短裤(腰带) [CE]", "其他", "", 2.2f),
    new ItemEntry("GEAR_DressingICrampons", "皮鞋(简易鞋底钉) [CE]", "其他", "", 1.25f),
    new ItemEntry("GEAR_DressingNCrampons", "皮鞋(鞋底钉) [CE]", "其他", "", 1f),
    new ItemEntry("GEAR_InsulatedICrampons", "橡胶靴(简易鞋底钉) [CE]", "其他", "", 2.25f),
    new ItemEntry("GEAR_InsulatedNCrampons", "橡胶靴(鞋底钉) [CE]", "其他", "", 2f),
    new ItemEntry("GEAR_InsulatedToolbelt", "雪花裤(腰带) [CE]", "其他", "", 1.2f),
    new ItemEntry("GEAR_JeansToolbelt", "牛仔裤(腰带) [CE]", "其他", "", 1.2f),
    new ItemEntry("GEAR_MinerToolbelt", "矿工裤子(腰带) [CE]", "其他", "", 0.7f),
    new ItemEntry("GEAR_MooseBagPlusScabbard", "驼鹿皮背包(枪套) [CE]", "其他", "", 0.5f),
    new ItemEntry("GEAR_MuklukICrampons", "皮制软靴(简易鞋底钉) [CE]", "其他", "", 2.25f),
    new ItemEntry("GEAR_MuklukNCrampons", "皮制软靴(鞋底钉) [CE]", "其他", "", 2f),
    new ItemEntry("GEAR_RunningICrampons", "跑鞋(简易鞋底钉) [CE]", "其他", "", 1.25f),
    new ItemEntry("GEAR_RunningNCrampons", "跑鞋(鞋底钉) [CE]", "其他", "", 1f),
    new ItemEntry("GEAR_SkiICrampons", "滑雪靴(简易鞋底钉) [CE]", "其他", "", 4.75f),
    new ItemEntry("GEAR_SkiNCrampons", "滑雪靴(鞋底钉) [CE]", "其他", "", 4.5f),
    new ItemEntry("GEAR_TrailICrampons", "越野鞋(简易鞋底钉) [CE]", "其他", "", 1.75f),
    new ItemEntry("GEAR_TrailNCrampons", "越野鞋(鞋底钉) [CE]", "其他", "", 1.5f),
    new ItemEntry("GEAR_WorkICrampons", "工作靴(简易鞋底钉) [CE]", "其他", "", 2.25f),
    new ItemEntry("GEAR_WorkNCrampons", "工作靴(鞋底钉) [CE]", "其他", "", 2f),
    new ItemEntry("GEAR_WorkToolbelt", "工作裤(腰带) [CE]", "其他", "", 1.7f),
    new ItemEntry("GEAR_BeanieCap", "豆豆帽 [TKG]", "衣物", "", 0.15f),
    new ItemEntry("GEAR_FarmBoots", "农夫的靴子 [TKG]", "衣物", "", 1f),
    new ItemEntry("GEAR_ImprovisedFaceMask", "口罩 [TKG]", "衣物", "", 0.05f),
    new ItemEntry("GEAR_MedicalFaceMask", "医用口罩 [TKG]", "衣物", "", 0.05f),
    new ItemEntry("GEAR_PrisonCoat", "加厚的飞行员夹克 [TKG]", "衣物", "", 1f),
    new ItemEntry("GEAR_PrisonPants", "囚裤 [TKG]", "衣物", "", 0.5f),
    new ItemEntry("GEAR_PrisonShirt", "囚服 [TKG]", "衣物", "", 0.25f),
    new ItemEntry("GEAR_SkiGoggles", "滑雪护目镜(自改) [TKG]", "衣物", "", 0.2f),
    new ItemEntry("GEAR_Skimask", "滑雪面罩 [TKG]", "衣物", "", 0.25f),
    new ItemEntry("GEAR_ccAirlinerBrandCard", "航运公司会员卡(自改) [Cards]", "材料", "", 0.01f),
    new ItemEntry("GEAR_ccBananaCard", "香蕉纪念卡 [Cards]", "材料", "", 0.01f),
    new ItemEntry("GEAR_ccBananaCard_Foil", "金箔香蕉纪念卡 [Cards]", "材料", "", 0.01f),
    new ItemEntry("GEAR_ccBananaCard_Holo", "全息香蕉纪念卡 [Cards]", "材料", "", 0.01f),
    new ItemEntry("GEAR_ccBearCard", "大熊队交易卡 [Cards]", "材料", "", 0.01f),
    new ItemEntry("GEAR_ccBearCard_Holo", "大熊队全息交易卡 [Cards]", "材料", "", 0.01f),
    new ItemEntry("GEAR_ccCaptainCard", "船长钥匙卡(自改) [Cards]", "材料", "", 0.01f),
    new ItemEntry("GEAR_ccCardBase", "cccardbase [Cards]", "材料", "", 0.01f),
    new ItemEntry("GEAR_ccCocoaCard", "热可可纪念卡(自改) [Cards]", "医疗", "", 0.01f, 1),
    new ItemEntry("GEAR_ccConemanCard", "科尼人卡牌(自改) [Cards]", "材料", "", 0.01f),
    new ItemEntry("GEAR_ccDarkwalkerCard", "暗行者卡牌(自改) [Cards]", "材料", "", 0.01f),
    new ItemEntry("GEAR_ccDarkwalkerCard_Foil", "金箔暗行者卡牌(自改) [Cards]", "材料", "", 0.01f),
    new ItemEntry("GEAR_ccDeadmanCard", "亡灵卡 [Cards]", "材料", "", 0.01f),
    new ItemEntry("GEAR_ccDeadmanCard_Holo", "亡灵全息卡 [Cards]", "材料", "", 0.01f),
    new ItemEntry("GEAR_ccInhabitantCard", "居民卡(自改) [Cards]", "材料", "", 0.01f),
    new ItemEntry("GEAR_ccModderBooster", "卡牌模组拓展包 [Cards]", "材料", "", 0.03f),
    new ItemEntry("GEAR_ccOldBearCard", "大熊卡牌 [Cards]", "材料", "", 0.01f),
    new ItemEntry("GEAR_ccPumpkinSoupCard", "南瓜汤纪念卡(自改) [Cards]", "医疗", "", 0.01f),
    new ItemEntry("GEAR_ccRifleCard", "步枪交易卡(自改) [Cards]", "材料", "", 0.01f),
    new ItemEntry("GEAR_ccSmokingCard", "吸烟警示卡(自改) [Cards]", "材料", "", 0.01f),
    new ItemEntry("GEAR_ccStoriesIBooster", "故事1卡牌扩展包 [Cards]", "材料", "", 0.03f),
    new ItemEntry("GEAR_ccTKGCard", "TKG卡牌(自改) [Cards]", "材料", "", 0.01f),
    new ItemEntry("GEAR_ccTLDevCard", "TLDev签名卡(自改) [Cards]", "材料", "", 0.01f),
    new ItemEntry("GEAR_ccTOTTCard", "工具交易卡(自改) [Cards]", "材料", "", 0.01f),
    new ItemEntry("GEAR_ccTourGuideCard", "导游纪念卡(自改) [Cards]", "材料", "", 0.01f),
    new ItemEntry("GEAR_ccTransportCard", "草原兔航运商务卡(自改) [Cards]", "材料", "", 0.01f),
    new ItemEntry("GEAR_ccWolfBrandCard", "林狼主题卡(自改) [Cards]", "材料", "", 0.01f),
    new ItemEntry("GEAR_ccWolfBrandCard_Holo", "林狼全息主题卡(自改) [Cards]", "材料", "", 0.01f),
    new ItemEntry("GEAR_MakeshiftBedroll", "拼布睡袋 [Cozy]", "工具", "", 1f),
    new ItemEntry("GEAR_MakeshiftBlanket", "拼布毯子 [Cozy]", "工具", "", 0.5f),
    new ItemEntry("GEAR_OldBlanket1", "老旧的毯子 [Cozy]", "工具", "", 1f),
    new ItemEntry("GEAR_OldBlanket2", "老旧的毯子 [Cozy]", "工具", "", 1f),
    new ItemEntry("GEAR_ActiveEmberBox", "阴燃的灰烬罐 [FirePk]", "材料", "", 0.35f),
    new ItemEntry("GEAR_BowDrill", "弓钻 [FirePk]", "材料", "", 1.5f),
    new ItemEntry("GEAR_EmberBox", "灰烬罐 [FirePk]", "材料", "", 0.35f),
    new ItemEntry("GEAR_FlintNSteel", "简易打火器 [FirePk]", "材料", "", 0.1f),
    new ItemEntry("GEAR_StrongFishingLine", "鱼线卷 [Fish]", "材料", "", 0.25f),
    new ItemEntry("GEAR_AuroraEnergyDrink", "极光能量饮料 [FoodTKG]", "食物", "", 0.25f, 300),
    new ItemEntry("GEAR_BeerBottle", "啤酒 [FoodTKG]", "食物", "", 0.5f, 250),
    new ItemEntry("GEAR_Bread", "薄饼面包 [FoodTKG]", "食物", "", 0.25f, 425),
    new ItemEntry("GEAR_CannedChili", "墨西哥辣味甜面酱罐头 [FoodTKG]", "食物", "", 0.4f, 520),
    new ItemEntry("GEAR_CannedChiliOpened", "墨西哥辣味甜面酱罐头 [FoodTKG]", "食物", "", 0.4f, 520),
    new ItemEntry("GEAR_CannedChiliPackage", "Large Canned Chili Package [FoodTKG]", "材料", "", 7.2f),
    new ItemEntry("GEAR_CannedChiliPackage2", "Small Canned Chili Package [FoodTKG]", "材料", "", 3.6f),
    new ItemEntry("GEAR_CannedMangos", "芒果罐头 [FoodTKG]", "食物", "", 0.6f, 500),
    new ItemEntry("GEAR_CannedPears", "梨罐头 [FoodTKG]", "食物", "", 0.6f, 500),
    new ItemEntry("GEAR_CannedPineapples", "苹果罐头 [FoodTKG]", "食物", "", 0.6f, 500),
    new ItemEntry("GEAR_CannedSpaghetti", "意式肉丸面罐头 [FoodTKG]", "食物", "", 0.4f, 725),
    new ItemEntry("GEAR_CannedSpaghettiOpened", "意式肉丸面罐头 [FoodTKG]", "食物", "", 0.4f, 725),
    new ItemEntry("GEAR_CannedSpaghettiPackage", "Large Canned Spaghetti Package [FoodTKG]", "材料", "", 7.2f),
    new ItemEntry("GEAR_CannedSpaghettiPackage2", "Small Canned Spaghetti Package [FoodTKG]", "材料", "", 3.6f),
    new ItemEntry("GEAR_CannedStew", "蔬菜炖肉罐头 [FoodTKG]", "食物", "", 0.4f, 900),
    new ItemEntry("GEAR_CannedStewOpened", "蔬菜炖肉罐头 [FoodTKG]", "食物", "", 0.4f, 900),
    new ItemEntry("GEAR_CannedStewPackage", "Large Canned Stews Package [FoodTKG]", "材料", "", 7.2f),
    new ItemEntry("GEAR_CannedStewPackage2", "Small Canned Stews Package [FoodTKG]", "材料", "", 3.6f),
    new ItemEntry("GEAR_CatFood", "猫食 [FoodTKG]", "食物", "", 0.4f, 400),
    new ItemEntry("GEAR_CatFoodPackage", "catfoodpackage [FoodTKG]", "材料", "", 7.2f),
    new ItemEntry("GEAR_CatFoodSmall", "金枪鱼罐头 [FoodTKG]", "食物", "", 0.1f, 200),
    new ItemEntry("GEAR_CerealHoney", "POPs蜂蜜麦片 [FoodTKG]", "食物", "", 0.2f, 720),
    new ItemEntry("GEAR_CerealHoneyPackage", "Large Cereal Honey Package [FoodTKG]", "材料", "", 3f),
    new ItemEntry("GEAR_CerealHoneyPackage2", "Small Cereal Honey Package [FoodTKG]", "材料", "", 2f),
    new ItemEntry("GEAR_CerealWholeGrain", "全谷麦片 [FoodTKG]", "食物", "", 0.2f, 600),
    new ItemEntry("GEAR_CerealWholeGrainPackage", "Large Cereal Whole Grain [FoodTKG]", "材料", "", 3f),
    new ItemEntry("GEAR_CerealWholeGrainPackage2", "Small Cereal Whole Grain [FoodTKG]", "材料", "", 2f),
    new ItemEntry("GEAR_CheesePackage", "奶酪棒 [FoodTKG]", "食物", "", 0.05f, 100),
    new ItemEntry("GEAR_CocoaPackage", "Large Hot Cocoa Package [FoodTKG]", "材料", "", 3.2f),
    new ItemEntry("GEAR_CocoaPackage2", "Small Hot Cocoa Package [FoodTKG]", "材料", "", 1.6f),
    new ItemEntry("GEAR_CookedApplePie", "苹果派 [FoodTKG]", "其他", "", 0.3f, 700),
    new ItemEntry("GEAR_CookedPierogi", "芝士煎饺 [FoodTKG]", "其他", "", 0.3f, 1000),
    new ItemEntry("GEAR_CookedPoutine", "肉汁奶酪薯条 [FoodTKG]", "其他", "", 0.3f, 250),
    new ItemEntry("GEAR_CookedSkilletPizza", "火腿披萨 [FoodTKG]", "其他", "", 0.4f, 1400),
    new ItemEntry("GEAR_CookedToastedSandwich", "芝士三明治 [FoodTKG]", "其他", "", 0.3f, 250),
    new ItemEntry("GEAR_Cookedperogi", "cookedperogi [FoodTKG]", "其他", "", 0.3f, 250),
    new ItemEntry("GEAR_Cookies", "曲奇饼干 [FoodTKG]", "食物", "", 0.1f, 225),
    new ItemEntry("GEAR_Cornflakes", "玉米片 [FoodTKG]", "食物", "", 0.2f, 600),
    new ItemEntry("GEAR_CornflakesPackage", "Large Cornflakes Package [FoodTKG]", "材料", "", 3f),
    new ItemEntry("GEAR_CornflakesPackage2", "Small Cornflakes Package [FoodTKG]", "材料", "", 2f),
    new ItemEntry("GEAR_CupMilk", "复水牛奶 [FoodTKG]", "食物", "", 0.15f, 150),
    new ItemEntry("GEAR_CupNoodles", "速食杯面 [FoodTKG]", "食物", "", 0.1f, 320),
    new ItemEntry("GEAR_CupNoodlesOpen", "速食杯面 [FoodTKG]", "食物", "", 0.13f, 380),
    new ItemEntry("GEAR_EmptyPackage", "Empty Package [FoodTKG]", "材料", "", 0.05f),
    new ItemEntry("GEAR_FlourBag", "精致面粉 [FoodTKG]", "食物", "", 1.5f, 10),
    new ItemEntry("GEAR_ForsakenSpirits", "被遗忘者咖啡鸡尾酒 [FoodTKG]", "医疗", "", 0.25f, 150),
    new ItemEntry("GEAR_ForsakenSpiritsPlastic", "被遗忘者茶调鸡尾酒 [FoodTKG]", "医疗", "", 0.25f, 125),
    new ItemEntry("GEAR_HoneyJar", "蜂蜜 [FoodTKG]", "食物", "", 0.25f, 850),
    new ItemEntry("GEAR_HotCocoaCup", "热可可 [FoodTKG]", "食物", "", 0.15f, 150),
    new ItemEntry("GEAR_Jalapeno", "墨西哥辣椒罐头 [FoodTKG]", "食物", "", 0.1f, 200),
    new ItemEntry("GEAR_ModChocolateBar", "黑巧克力 [FoodTKG]", "食物", "", 0.1f, 540),
    new ItemEntry("GEAR_ModSyrup", "枫糖浆 [FoodTKG]", "食物", "", 0.3f, 850),
    new ItemEntry("GEAR_MountainSoda", "尖峰苏打水 [FoodTKG]", "食物", "", 0.25f, 300),
    new ItemEntry("GEAR_MountainSodaPlastic", "尖峰苏打水 [FoodTKG]", "食物", "", 0.25f, 250),
    new ItemEntry("GEAR_NanaimoBar", "纳奈莫条 [FoodTKG]", "食物", "", 0.35f, 1750),
    new ItemEntry("GEAR_RedWineBottle", "红酒 [FoodTKG]", "食物", "", 0.75f, 1000),
    new ItemEntry("GEAR_RiceCooked", "长粒熟米饭 [FoodTKG]", "食物", "", 0.75f, 900),
    new ItemEntry("GEAR_SPAM", "斯帕姆午餐肉罐头 [FoodTKG]", "食物", "", 0.2f, 500),
    new ItemEntry("GEAR_SoyRamen", "方便面 [FoodTKG]", "食物", "", 0.1f, 350),
    new ItemEntry("GEAR_SoyRamenCooked", "煮面 [FoodTKG]", "食物", "", 0.14f, 420),
    new ItemEntry("GEAR_UnCookedApplePie", "苹果派 [FoodTKG]", "其他", "", 0.3f, 100),
    new ItemEntry("GEAR_UnCookedPierogi", "芝士煎饺 [FoodTKG]", "其他", "", 0.3f, 100),
    new ItemEntry("GEAR_UnCookedPoutine", "肉汁奶酪薯条 [FoodTKG]", "其他", "", 0.3f, 100),
    new ItemEntry("GEAR_UnCookedSkilletPizza", "火腿披萨 [FoodTKG]", "其他", "", 0.4f, 100),
    new ItemEntry("GEAR_UnCookedToastedSandwich", "芝士三明治 [FoodTKG]", "其他", "", 0.3f, 100),
    new ItemEntry("GEAR_Uncookedperogi", "uncookedperogi [FoodTKG]", "其他", "", 0.3f, 100),
    new ItemEntry("GEAR_VodkaBottle", "精酿伏特加 [FoodTKG]", "医疗", "", 0.5f, 260),
    new ItemEntry("GEAR_WhiskyFlask", "秘制药酒壶 [FoodTKG]", "医疗", "", 0.2f),
    new ItemEntry("GEAR_ABCSoup", "字母汤 [CW]", "食物", "", 0.5f, 600),
    new ItemEntry("GEAR_applesaucePryanik", "苹果糕饼 [CW]", "食物", "", 0.35f, 300),
    new ItemEntry("GEAR_bananaChips", "香蕉脆片 [CW]", "食物", "", 0.1f, 500),
    new ItemEntry("GEAR_crabSnack", "蟹肉麦片 [CW]", "食物", "", 0.08f, 320),
    new ItemEntry("GEAR_figConfiture", "无花果酱 [CW]", "食物", "", 0.4f, 900),
    new ItemEntry("GEAR_glintweinCup", "热红酒(自改) [CW]", "医疗", "", 0.5f, 200),
    new ItemEntry("GEAR_hematogen", "血原棒 [CW]", "医疗", "", 0.05f, 150),
    new ItemEntry("GEAR_honeyNuts", "蜂蜜坚果 [CW]", "食物", "", 0.8f, 3000),
    new ItemEntry("GEAR_hotSpringSoda", "温泉苏打水 [CW]", "食物", "", 0.4f, 120),
    new ItemEntry("GEAR_icecreamCup", "威化冰淇淋甜筒 [CW]", "食物", "", 0.12f, 300),
    new ItemEntry("GEAR_jubileeCookies", "姜味曲奇 [CW]", "食物", "", 0.25f, 800),
    new ItemEntry("GEAR_kvass", "格瓦斯 [CW]", "食物", "", 0.6f, 150),
    new ItemEntry("GEAR_latteDrops", "水滴咖啡 [CW]", "食物", "", 0.06f, 35),
    new ItemEntry("GEAR_lecso", "Lecsó烩菜 [CW]", "食物", "", 0.6f, 300),
    new ItemEntry("GEAR_marinaraMackerel", "酱汁鲭鱼 [CW]", "食物", "", 0.25f, 250),
    new ItemEntry("GEAR_mysteryCake", "巧克力果仁威化饼 [CW]", "食物", "", 0.15f, 600),
    new ItemEntry("GEAR_nordShoreChocolate", "黑巧克力(盐焦糖味) [CW]", "食物", "", 0.125f, 500),
    new ItemEntry("GEAR_oatsBowl", "燕麦粥 [CW]", "食物", "", 0.4f, 250),
    new ItemEntry("GEAR_pinenutBrittle", "松子糖 [CW]", "食物", "", 0.4f, 1200),
    new ItemEntry("GEAR_rahatLokum", "土耳其软糖 [CW]", "食物", "", 0.3f, 900),
    new ItemEntry("GEAR_roastedAlmonds", "烤杏仁 [CW]", "食物", "", 0.06f, 240),
    new ItemEntry("GEAR_solitudeCider", "野苹果酒 [CW]", "食物", "", 0.4f, 180),
    new ItemEntry("GEAR_strawberryPlombir", "普隆别尔草莓雪糕 [CW]", "食物", "", 0.1f, 200),
    new ItemEntry("GEAR_tunaPate", "金枪鱼肉酱 [CW]", "食物", "", 0.1f, 200),
    new ItemEntry("GEAR_AcornBrandyBarrel", "M-橡子白兰地酒桶 [Brew]", "工具", "", 15f),
    new ItemEntry("GEAR_AcornBrandyBarrelReady", "橡子白兰地酒桶(成品) [Brew]", "材料", "", 15f),
    new ItemEntry("GEAR_Barrel", "M-酿酒桶 [Brew]", "工具", "", 10f),
    new ItemEntry("GEAR_BirchBarkBeerBarrel", "M-桦树皮啤酒桶 [Brew]", "工具", "", 15f),
    new ItemEntry("GEAR_BirchBarkBeerBarrelReady", "桦树皮啤酒桶(成品) [Brew]", "材料", "", 15f),
    new ItemEntry("GEAR_BurdockMoonshineBarrel", "M-牛蒡烈酒酒桶 [Brew]", "工具", "", 15f),
    new ItemEntry("GEAR_BurdockMoonshineBarrelReady", "牛蒡烈酒酒桶(成品) [Brew]", "材料", "", 15f),
    new ItemEntry("GEAR_CatTailRumBarrel", "M-香蒲朗姆酒酒桶 [Brew]", "工具", "", 15f),
    new ItemEntry("GEAR_CatTailRumBarrelReady", "香蒲朗姆酒酒桶(成品) [Brew]", "材料", "", 15f),
    new ItemEntry("GEAR_LichAcornBrandy", "橡子白兰地 [Brew]", "食物", "", 1f, 1000),
    new ItemEntry("GEAR_LichBirchBarkBeer", "桦树皮啤酒 [Brew]", "食物", "", 1f, 500),
    new ItemEntry("GEAR_LichBurdockMoonshine", "牛蒡烈酒 [Brew]", "食物", "", 1f, 1000),
    new ItemEntry("GEAR_LichCatTailRum", "香蒲朗姆酒 [Brew]", "食物", "", 1f, 900),
    new ItemEntry("GEAR_LichReishiWhisky", "灵芝威士忌 [Brew]", "食物", "", 1f, 1000),
    new ItemEntry("GEAR_LichRosehipWineAge1", "1阶段陈酿玫瑰果酒 [Brew]", "食物", "", 1f, 800),
    new ItemEntry("GEAR_LichRosehipWineAge2", "2阶段陈酿玫瑰果酒 [Brew]", "食物", "", 1f, 1200),
    new ItemEntry("GEAR_LichRosehipWineAge3", "3阶段陈酿玫瑰果酒 [Brew]", "食物", "", 1f, 2100),
    new ItemEntry("GEAR_LichVodka", "自酿伏特加 [Brew]", "食物", "", 1f, 1050),
    new ItemEntry("GEAR_PotatoSack", "土豆麻袋 [Brew]", "其他", "", 7f),
    new ItemEntry("GEAR_ReishiWhiskyBarrel", "M-灵芝威士忌酒桶 [Brew]", "工具", "", 15f),
    new ItemEntry("GEAR_ReishiWhiskyBarrelReady", "灵芝威士忌酒桶(成品) [Brew]", "材料", "", 15f),
    new ItemEntry("GEAR_RosehipWineBarrel", "M-玫瑰果酒桶 [Brew]", "工具", "", 15f),
    new ItemEntry("GEAR_RosehipWineBarrelReadyAge1", "玫瑰果酒桶1阶段陈酿(成品) [Brew]", "工具", "", 15f),
    new ItemEntry("GEAR_RosehipWineBarrelReadyAge2", "玫瑰果酒桶2阶段陈酿(成品) [Brew]", "工具", "", 15f),
    new ItemEntry("GEAR_RosehipWineBarrelReadyAge3", "玫瑰果酒桶3阶段陈酿(成品) [Brew]", "工具", "", 15f),
    new ItemEntry("GEAR_VodkaBarrel", "M-自酿伏特加酒桶 [Brew]", "工具", "", 15f),
    new ItemEntry("GEAR_VodkaBarrelReady", "自酿伏特加酒桶(成品) [Brew]", "材料", "", 15f),
    new ItemEntry("GEAR_Yeast", "酵母菌 [Brew]", "材料", "", 0.2f),
    new ItemEntry("GEAR_Berrysoap", "肥皂果 [Greenery]", "食物", "", 0.01f, 50),
    new ItemEntry("GEAR_Blueberries", "蓝莓果 [Greenery]", "食物", "", 0.01f, 50),
    new ItemEntry("GEAR_CookedBlueberryPie", "蓝莓派 [Greenery]", "食物", "", 0.2f, 250),
    new ItemEntry("GEAR_CookedSoapberryPie", "肥皂果派 [Greenery]", "食物", "", 0.2f, 250),
    new ItemEntry("GEAR_DeadMatter", "有机废物 [Greenery]", "材料", "", 0.05f),
    new ItemEntry("GEAR_DeadPlanterBig", "枯萎的植物 [Greenery]", "材料", "", 1.2f),
    new ItemEntry("GEAR_DeadPlanterBox", "枯萎的植物 [Greenery]", "材料", "", 2.2f),
    new ItemEntry("GEAR_DeadPlanterHumid", "枯萎的植物 [Greenery]", "材料", "", 2.3f),
    new ItemEntry("GEAR_DeadPlanterSmall", "枯萎的植物 [Greenery]", "材料", "", 0.2f),
    new ItemEntry("GEAR_DirtBox", "盒装泥土 [Greenery]", "工具", "", 2.2f),
    new ItemEntry("GEAR_DirtCan", "罐装泥土 [Greenery]", "工具", "", 0.2f),
    new ItemEntry("GEAR_DirtHumid", "盒装泥土(加湿器) [Greenery]", "工具", "", 2.3f),
    new ItemEntry("GEAR_DirtPot", "盆栽泥土 [Greenery]", "工具", "", 1.2f),
    new ItemEntry("GEAR_DistilledWater", "蒸馏水 [Greenery]", "材料", "", 0.5f),
    new ItemEntry("GEAR_GardeningMesh", "种植网 [Greenery]", "材料", "", 0.3f),
    new ItemEntry("GEAR_GardeningTools", "种植工具套件 [Greenery]", "工具", "", 0.6f),
    new ItemEntry("GEAR_GardeningToolsImprovised", "简易种植工具套件 [Greenery]", "工具", "", 1f),
    new ItemEntry("GEAR_HerbLeavesHarvested", "草本果实 [Greenery]", "食物", "", 5f),
    new ItemEntry("GEAR_HerbalTeaHomemade", "自制的草药茶 [Greenery]", "食物", "", 0.1f, 100),
    new ItemEntry("GEAR_HumidKit", "加湿器套件 [Greenery]", "材料", "", 2.2f),
    new ItemEntry("GEAR_JamBlueberry", "蓝莓酱 [Greenery]", "食物", "", 0.5f, 600),
    new ItemEntry("GEAR_JamSoapberry", "肥皂果酱 [Greenery]", "食物", "", 0.5f, 600),
    new ItemEntry("GEAR_PlantNutrients", "植物肥料 [Greenery]", "材料", "", 0.2f),
    new ItemEntry("GEAR_PlantNutrientsCrafted", "植物肥料 [Greenery]", "材料", "", 0.2f),
    new ItemEntry("GEAR_PlantWater", "雨滴 [Greenery]", "材料", "", 0.7f),
    new ItemEntry("GEAR_PlanterBig", "栽培盆 [Greenery]", "材料", "", 1.2f),
    new ItemEntry("GEAR_PlanterBlueberries1", "蓝莓种植器(成熟) [Greenery]", "材料", "", 2.4f),
    new ItemEntry("GEAR_PlanterBlueberries2", "蓝莓种植器(幼苗) [Greenery]", "材料", "", 2.35f),
    new ItemEntry("GEAR_PlanterBox", "金属盒种植器 [Greenery]", "材料", "", 2.2f),
    new ItemEntry("GEAR_PlanterBurdockBig1", "牛蒡盆栽(成熟) [Greenery]", "材料", "", 1.3f),
    new ItemEntry("GEAR_PlanterBurdockBig2", "牛蒡盆栽(幼苗) [Greenery]", "材料", "", 1.25f),
    new ItemEntry("GEAR_PlanterBurdockSmall1", "牛蒡栽培罐(成熟) [Greenery]", "材料", "", 0.3f),
    new ItemEntry("GEAR_PlanterBurdockSmall2", "牛蒡栽培罐(幼苗) [Greenery]", "材料", "", 0.25f),
    new ItemEntry("GEAR_PlanterCarrot1", "胡萝卜种植器(成熟) [Greenery]", "材料", "", 2.3f),
    new ItemEntry("GEAR_PlanterCarrot2", "胡萝卜种植器(幼苗) [Greenery]", "材料", "", 2.3f),
    new ItemEntry("GEAR_PlanterCattailBig1", "香蒲盆栽(成熟) [Greenery]", "材料", "", 1.3f),
    new ItemEntry("GEAR_PlanterCattailBig2", "香蒲盆栽(幼苗) [Greenery]", "材料", "", 1.25f),
    new ItemEntry("GEAR_PlanterCattailSmall1", "香蒲栽培罐(成熟) [Greenery]", "材料", "", 0.3f),
    new ItemEntry("GEAR_PlanterCattailSmall2", "香蒲栽培罐(幼苗) [Greenery]", "材料", "", 0.25f),
    new ItemEntry("GEAR_PlanterHerbs1", "草本植物种植器(成熟) [Greenery]", "材料", "", 2.4f),
    new ItemEntry("GEAR_PlanterHerbs2", "草本植物种植器(幼苗) [Greenery]", "材料", "", 2.35f),
    new ItemEntry("GEAR_PlanterHumid", "金属盒种植器(加湿器) [Greenery]", "材料", "", 2.3f),
    new ItemEntry("GEAR_PlanterOldmanBig1", "胡须地衣盆栽(成熟) [Greenery]", "材料", "", 1.3f),
    new ItemEntry("GEAR_PlanterOldmanBig2", "胡须地衣盆栽(幼苗) [Greenery]", "材料", "", 1.25f),
    new ItemEntry("GEAR_PlanterPotato1", "土豆种植器(成熟) [Greenery]", "材料", "", 2.3f),
    new ItemEntry("GEAR_PlanterPotato2", "土豆种植器(幼苗) [Greenery]", "材料", "", 2.3f),
    new ItemEntry("GEAR_PlanterReishiBig1", "灵芝盆栽(成熟) [Greenery]", "材料", "", 1.3f),
    new ItemEntry("GEAR_PlanterReishiBig2", "灵芝盆栽(幼苗) [Greenery]", "材料", "", 1.25f),
    new ItemEntry("GEAR_PlanterRosehipBig1", "玫瑰果盆栽(成熟) [Greenery]", "材料", "", 1.3f),
    new ItemEntry("GEAR_PlanterRosehipBig2", "玫瑰果盆栽(幼苗) [Greenery]", "材料", "", 1.25f),
    new ItemEntry("GEAR_PlanterRosehipSmall1", "玫瑰果栽培罐(成熟) [Greenery]", "材料", "", 0.3f),
    new ItemEntry("GEAR_PlanterRosehipSmall2", "玫瑰果栽培罐(幼苗) [Greenery]", "材料", "", 0.25f),
    new ItemEntry("GEAR_PlanterSmall", "栽培罐 [Greenery]", "材料", "", 0.2f),
    new ItemEntry("GEAR_PlanterSoapberries1", "肥皂果种植器(成熟) [Greenery]", "材料", "", 2.4f),
    new ItemEntry("GEAR_PlanterSoapberries2", "肥皂果种植器(幼苗) [Greenery]", "材料", "", 2.35f),
    new ItemEntry("GEAR_SeedsBlue", "蓝莓果种子(包) [Greenery]", "材料", "", 0.1f),
    new ItemEntry("GEAR_SeedsBlueExtracted", "蓝莓果种子(罐) [Greenery]", "材料", "", 0.2f),
    new ItemEntry("GEAR_SeedsBurdockExtracted", "牛蒡种子 [Greenery]", "材料", "", 0.2f),
    new ItemEntry("GEAR_SeedsCarrotExtracted", "胡萝卜种子 [Greenery]", "材料", "", 0.2f),
    new ItemEntry("GEAR_SeedsHerbExtracted", "草本植物种子(罐) [Greenery]", "材料", "", 0.2f),
    new ItemEntry("GEAR_SeedsHerbs", "草本植物种子(包) [Greenery]", "材料", "", 0.1f),
    new ItemEntry("GEAR_SeedsLichenExtracted", "胡须地衣种子 [Greenery]", "材料", "", 0.2f),
    new ItemEntry("GEAR_SeedsReishiExtracted", "灵芝种子 [Greenery]", "材料", "", 0.2f),
    new ItemEntry("GEAR_SeedsRoseExtracted", "玫瑰果种子 [Greenery]", "材料", "", 0.2f),
    new ItemEntry("GEAR_SeedsSoap", "肥皂果种子(包) [Greenery]", "材料", "", 0.1f),
    new ItemEntry("GEAR_SeedsSoapExtracted", "肥皂果种子(罐) [Greenery]", "材料", "", 0.2f),
    new ItemEntry("GEAR_SoilBag", "土壤 [Greenery]", "材料", "", 1f),
    new ItemEntry("GEAR_UncookedBlueberryPie", "蓝莓派(生) [Greenery]", "食物", "", 0.2f, 50),
    new ItemEntry("GEAR_UncookedSoapberryPie", "肥皂果派(生) [Greenery]", "食物", "", 0.2f, 50),
    new ItemEntry("GEAR_CattailPile005", "香蒲茎干打包X5 [Piles]", "材料", "", 0.25f, 750),
    new ItemEntry("GEAR_CharcoalPile010", "木炭打包X10 [Piles]", "材料", "", 1f),
    new ItemEntry("GEAR_CoalPile004", "煤炭打包X4 [Piles]", "材料", "", 1.2f),
    new ItemEntry("GEAR_HardwoodPile005", "冷杉木打包X5 [Piles]", "材料", "", 5f),
    new ItemEntry("GEAR_RwoodPile010", "旧木材打包X10 [Piles]", "材料", "", 2.5f),
    new ItemEntry("GEAR_ScrapPile010", "废金属打包X10 [Piles]", "材料", "", 2f),
    new ItemEntry("GEAR_SoftwoodPile005", "雪松木打包X5 [Piles]", "材料", "", 2.5f),
    new ItemEntry("GEAR_StickPile010", "树枝打包X10 [Piles]", "材料", "", 1.5f),
    new ItemEntry("GEAR_StickPile050", "树枝打包X50 [Piles]", "材料", "", 7.5f),
    new ItemEntry("GEAR_StickPile050F", "树枝横向打包X50 [Piles]", "材料", "", 7.5f),
    new ItemEntry("GEAR_StonePile010", "石块打包X10 [Piles]", "材料", "", 1.5f),
    new ItemEntry("GEAR_LichPlush1", "lichplush1 [Plushie]", "衣物", "", 0.25f),
    new ItemEntry("GEAR_LichPlush10", "lichplush10 [Plushie]", "衣物", "", 0.25f),
    new ItemEntry("GEAR_LichPlush11", "lichplush11 [Plushie]", "衣物", "", 0.25f),
    new ItemEntry("GEAR_LichPlush12", "lichplush12 [Plushie]", "衣物", "", 0.25f),
    new ItemEntry("GEAR_LichPlush13", "lichplush13 [Plushie]", "衣物", "", 0.25f),
    new ItemEntry("GEAR_LichPlush2", "lichplush2 [Plushie]", "衣物", "", 0.25f),
    new ItemEntry("GEAR_LichPlush3", "lichplush3 [Plushie]", "衣物", "", 0.25f),
    new ItemEntry("GEAR_LichPlush4", "lichplush4 [Plushie]", "衣物", "", 0.25f),
    new ItemEntry("GEAR_LichPlush5", "lichplush5 [Plushie]", "衣物", "", 0.25f),
    new ItemEntry("GEAR_LichPlush6", "lichplush6 [Plushie]", "衣物", "", 0.25f),
    new ItemEntry("GEAR_LichPlush7", "lichplush7 [Plushie]", "衣物", "", 0.25f),
    new ItemEntry("GEAR_LichPlush8", "lichplush8 [Plushie]", "衣物", "", 0.25f),
    new ItemEntry("GEAR_LichPlush9", "lichplush9 [Plushie]", "衣物", "", 0.25f),
    new ItemEntry("GEAR_LichStackCanOfDogfood", "打包狗粮 [Stack]", "材料", "", 2.7f),
    new ItemEntry("GEAR_LichStackCanOfPeach", "顶级桃子包裹 [Stack]", "食物", "", 2.25f),
    new ItemEntry("GEAR_LichStackCanOfPorkandbeans", "猪肉扁豆包裹 [Stack]", "食物", "", 2.25f),
    new ItemEntry("GEAR_LichStackCanOfTomatosoup", "番茄汤包裹 [Stack]", "食物", "", 2.25f),
    new ItemEntry("GEAR_LichStackChocolatebar", "打包巧克力棒 [Stack]", "材料", "", 2f),
    new ItemEntry("GEAR_LichStackCloth", "打包布料 [Stack]", "材料", "", 1f),
    new ItemEntry("GEAR_LichStackEnergybar", "打包能量棒 [Stack]", "材料", "", 2f),
    new ItemEntry("GEAR_LichStackFlareRed", "打包信号棒 [Stack]", "材料", "", 2f),
    new ItemEntry("GEAR_LichStackGranolabar", "打包燕麦卷 [Stack]", "材料", "", 2f),
    new ItemEntry("GEAR_LichStackHideBear", "打包熊皮 [Stack]", "材料", "", 5f),
    new ItemEntry("GEAR_LichStackHideDeer", "打包鹿皮 [Stack]", "材料", "", 5f),
    new ItemEntry("GEAR_LichStackHideMoose", "打包驼鹿皮 [Stack]", "材料", "", 5f),
    new ItemEntry("GEAR_LichStackHideRabbit", "打包兔皮 [Stack]", "材料", "", 1f),
    new ItemEntry("GEAR_LichStackHideWolf", "打包狼皮 [Stack]", "材料", "", 5f),
    new ItemEntry("GEAR_LichStackMeatBear", "打包熊肉 [Stack]", "材料", "", 5f),
    new ItemEntry("GEAR_LichStackMeatDeer", "打包鹿肉 [Stack]", "材料", "", 5f),
    new ItemEntry("GEAR_LichStackMeatMoose", "打包驼鹿肉 [Stack]", "材料", "", 5f),
    new ItemEntry("GEAR_LichStackMeatRabbit", "打包兔肉 [Stack]", "材料", "", 5f),
    new ItemEntry("GEAR_LichStackMeatWolf", "打包狼肉 [Stack]", "材料", "", 5f),
    new ItemEntry("GEAR_LichStackNewspaper1", "打包报纸卷 [Stack]", "其他", "", 1f),
    new ItemEntry("GEAR_LichStackNewspaper2", "打包纸堆 [Stack]", "其他", "", 1f),
    new ItemEntry("GEAR_LichStackNewspaper3", "打包报纸 [Stack]", "其他", "", 1f),
    new ItemEntry("GEAR_LichStackRecycledcan", "打包空罐 [Stack]", "材料", "", 1f),
    new ItemEntry("GEAR_LichStackSpraypaint", "打包油漆喷灌 [Stack]", "材料", "", 2f),
    new ItemEntry("GEAR_LichStackWater", "10L水壶 [Stack]", "材料", "", 5f),
    new ItemEntry("GEAR_SignL", "神秘的路标 [Lithar]", "其他", "", 1.5f),
    new ItemEntry("GEAR_BirchWood", "桦树木 [Wood]", "材料", "", 0.5f),
    new ItemEntry("GEAR_BirchWoodPile5", "一堆桦树木x5 [Wood]", "材料", "", 2.5f),
    new ItemEntry("GEAR_OakFireWood", "橡树木 [Wood]", "材料", "", 0.75f),
    new ItemEntry("GEAR_OakFireWoodPile5", "一堆橡树木x5 [Wood]", "材料", "", 3.75f),
    new ItemEntry("GEAR_PineNeedle", "松针 [Pine]", "材料", "", 0.1f),
    new ItemEntry("GEAR_PineNeedleDried", "风干的松针 [Pine]", "材料", "", 0.1f),
    new ItemEntry("GEAR_PineNeedleTea", "松针茶 [Pine]", "食物", "", 0.15f, 100),
    new ItemEntry("GEAR_CattailRhizomeCooked", "烤香蒲根 [Ranger]", "其他", "", 0.2f, 50),
    new ItemEntry("GEAR_CookedBearStew", "M-熊肉乱炖 [Ranger]", "其他", "", 0.35f, 920),
    new ItemEntry("GEAR_CookedMooseStew", "M-驼鹿肉乱炖 [Ranger]", "其他", "", 0.35f, 940),
    new ItemEntry("GEAR_CookedWolfStew", "M-狼肉乱炖 [Ranger]", "其他", "", 0.35f, 810),
    new ItemEntry("GEAR_RabbitRiverSallad", "兔肉拌菜 [Ranger]", "其他", "", 0.65f, 600),
    new ItemEntry("GEAR_AppleSauceJar", "applesaucejar [Retro]", "食物", "", 0.5f, 300),
    new ItemEntry("GEAR_AppleSnacks", "applesnacks [Retro]", "食物", "", 0.5f, 600),
    new ItemEntry("GEAR_BabyFoodBanana", "babyfoodbanana [Retro]", "食物", "", 0.2f, 120),
    new ItemEntry("GEAR_BabyFoodBerries", "babyfoodberries [Retro]", "食物", "", 0.2f, 120),
    new ItemEntry("GEAR_BabyFoodCarrot", "babyfoodcarrot [Retro]", "食物", "", 0.2f, 120),
    new ItemEntry("GEAR_BabyFoodPeas", "babyfoodpeas [Retro]", "食物", "", 0.2f, 120),
    new ItemEntry("GEAR_BakedBeans", "bakedbeans [Retro]", "食物", "", 0.5f, 600),
    new ItemEntry("GEAR_BakedBeansOpened", "bakedbeansopened [Retro]", "食物", "", 0.5f, 600),
    new ItemEntry("GEAR_CheeseDoodles", "cheesedoodles [Retro]", "食物", "", 0.2f, 900),
    new ItemEntry("GEAR_ChickenMeatballs", "chickenmeatballs [Retro]", "食物", "", 0.5f, 700),
    new ItemEntry("GEAR_ChickenMeatballsOpened", "chickenmeatballsopened [Retro]", "食物", "", 0.5f, 700),
    new ItemEntry("GEAR_CookiesJam", "cookiesjam [Retro]", "食物", "", 0.3f, 850),
    new ItemEntry("GEAR_CrushedTomatoes", "crushedtomatoes [Retro]", "食物", "", 0.5f, 160),
    new ItemEntry("GEAR_CrushedTomatoesOpened", "crushedtomatoesopened [Retro]", "食物", "", 0.5f, 160),
    new ItemEntry("GEAR_DriedRaisins", "driedraisins [Retro]", "食物", "", 0.2f, 500),
    new ItemEntry("GEAR_GroundBeef", "groundbeef [Retro]", "食物", "", 0.4f, 700),
    new ItemEntry("GEAR_GroundBeefOpened", "groundbeefopened [Retro]", "食物", "", 0.4f, 700),
    new ItemEntry("GEAR_MacCheeseCooked", "maccheesecooked [Retro]", "食物", "", 0.2f, 450),
    new ItemEntry("GEAR_MashedPotatoesCooked", "mashedpotatoescooked [Retro]", "食物", "", 0.2f, 400),
    new ItemEntry("GEAR_MixedNuts", "mixednuts [Retro]", "食物", "", 0.2f, 1200),
    new ItemEntry("GEAR_OrangeBiscuits", "orangebiscuits [Retro]", "食物", "", 0.3f, 750),
    new ItemEntry("GEAR_Pineapples", "pineapples [Retro]", "食物", "", 0.5f, 250),
    new ItemEntry("GEAR_PineapplesOpened", "pineapplesopened [Retro]", "食物", "", 0.5f, 250),
    new ItemEntry("GEAR_PremiumPastaCooked", "premiumpastacooked [Retro]", "食物", "", 0.2f, 400),
    new ItemEntry("GEAR_Sausages", "sausages [Retro]", "食物", "", 0.5f, 600),
    new ItemEntry("GEAR_SausagesOpened", "sausagesopened [Retro]", "食物", "", 0.5f, 600),
    new ItemEntry("GEAR_SoyMilk", "soymilk [Retro]", "食物", "", 0.5f, 300),
    new ItemEntry("GEAR_SwedishMeatballs", "swedishmeatballs [Retro]", "食物", "", 0.5f, 700),
    new ItemEntry("GEAR_SwedishMeatballsOpened", "swedishmeatballsopened [Retro]", "食物", "", 0.5f, 700),
    new ItemEntry("GEAR_TrailMix", "trailmix [Retro]", "食物", "", 0.2f, 900),
    new ItemEntry("GEAR_SnowDog", "S-雪狗 [Snow]", "材料", "", 3f),
    new ItemEntry("GEAR_SnowMen", "S-雪人 [Snow]", "材料", "", 13f),
    new ItemEntry("GEAR_SnowMister", "S-雪先生 [Snow]", "材料", "", 10f),
    new ItemEntry("GEAR_AcornCoffeeCupSugar", "橡实咖啡(糖) [Stalker]", "食物", "", 0.1f, 100),
    new ItemEntry("GEAR_Anabiotics", "镇静剂 [Stalker]", "医疗", "", 0.15f, 1),
    new ItemEntry("GEAR_BirchbarkTeaJam", "桦树皮茶(果酱) [Stalker]", "医疗", "", 0.1f, 100),
    new ItemEntry("GEAR_BirchbarkTeaSugar", "桦树皮茶(糖) [Stalker]", "医疗", "", 0.1f, 100),
    new ItemEntry("GEAR_BurdockTeaJam", "牛蒡茶(果酱) [Stalker]", "医疗", "", 0.1f, 100),
    new ItemEntry("GEAR_BurdockTeaSugar", "牛蒡茶(糖) [Stalker]", "医疗", "", 0.1f, 100),
    new ItemEntry("GEAR_CigarettePackMarlboro", "万宝路香烟 [Stalker]", "医疗", "", 0.1f),
    new ItemEntry("GEAR_CigarettePackOld", "好彩香烟 [Stalker]", "医疗", "", 0.1f),
    new ItemEntry("GEAR_CoffeeCupSugar", "咖啡(糖) [Stalker]", "食物", "", 0.1f, 100),
    new ItemEntry("GEAR_CookedBannockAcornJam", "橡实薄饼(果酱) [Stalker]", "食物", "", 0.1f, 250),
    new ItemEntry("GEAR_CookedBannockAcornSugar", "橡实薄饼(糖) [Stalker]", "食物", "", 0.1f, 250),
    new ItemEntry("GEAR_CookedBannockJam", "薄饼(果酱) [Stalker]", "食物", "", 0.1f, 200),
    new ItemEntry("GEAR_CookedBannockSugar", "薄饼(糖) [Stalker]", "食物", "", 0.1f, 200),
    new ItemEntry("GEAR_CookedPorridgeJam", "燕麦粥(果酱) [Stalker]", "食物", "", 0.2f, 350),
    new ItemEntry("GEAR_CookedPorridgeSugar", "燕麦粥(糖) [Stalker]", "食物", "", 0.2f, 350),
    new ItemEntry("GEAR_FirstAidKitPainkiller", "医药箱(自改) [Stalker]", "医疗", "", 2f),
    new ItemEntry("GEAR_GreenTeaCupJam", "草药茶(果酱) [Stalker]", "食物", "", 0.1f, 100),
    new ItemEntry("GEAR_GreenTeaCupSugar", "草药茶(糖) [Stalker]", "食物", "", 0.1f, 100),
    new ItemEntry("GEAR_NaturalBandage", "牛蒡敷料 [Stalker]", "医疗", "", 0.15f),
    new ItemEntry("GEAR_NoteNaturalBandage", "牛蒡敷料旧笔记 [Stalker]", "其他", "", 0.1f),
    new ItemEntry("GEAR_PainkillerIbuprofen", "布洛芬 [Stalker]", "医疗", "", 0.1f),
    new ItemEntry("GEAR_PainkillerMorphineVial", "吗啡 [Stalker]", "医疗", "", 0.35f),
    new ItemEntry("GEAR_ReishiTeaJam", "灵芝茶(果酱) [Stalker]", "医疗", "", 0.1f, 100),
    new ItemEntry("GEAR_ReishiTeaSugar", "灵芝茶(糖) [Stalker]", "医疗", "", 0.1f, 100),
    new ItemEntry("GEAR_RoseHipTeaJam", "玫瑰果茶(果酱) [Stalker]", "医疗", "", 0.1f, 100),
    new ItemEntry("GEAR_RoseHipTeaSugar", "玫瑰果茶(糖) [Stalker]", "医疗", "", 0.1f, 100),
    new ItemEntry("GEAR_RosehipJam", "玫瑰果酱 [Stalker]", "食物", "", 0.5f, 150),
    new ItemEntry("GEAR_SleepingPills", "安眠药 [Stalker]", "医疗", "", 0.1f, 2),
    new ItemEntry("GEAR_SugarA", "糖 [Stalker]", "食物", "", 0.25f),
    new ItemEntry("GEAR_UncookedRosehipJam", "生玫瑰果酱 [Stalker]", "食物", "", 0.5f, 250),
    new ItemEntry("GEAR_BookBigOne", "当地传说-湖主(Mod) [Story]", "材料", "", 0.5f),
    new ItemEntry("GEAR_BookGhostStag", "当地传说-幽灵鹿(Mod) [Story]", "材料", "", 0.5f),
    new ItemEntry("GEAR_BookLostCave", "当地传说-迷失的洞穴(Mod) [Story]", "材料", "", 0.5f),
    new ItemEntry("GEAR_BookPlantsGuide", "大熊岛药用植物 [Story]", "材料", "", 0.5f),
    new ItemEntry("GEAR_BookSasquatch", "当地传说-北美野人(Mod) [Story]", "材料", "", 0.5f),
    new ItemEntry("GEAR_FlyerBingo", "旧秩序 [Story]", "其他", "", 0.1f),
    new ItemEntry("GEAR_GoldCross", "教堂圣器 [Story]", "其他", "", 0.2f),
    new ItemEntry("GEAR_Goldnuggeta", "金块 [Story]", "其他", "", 0.3f),
    new ItemEntry("GEAR_IDcard", "虎鲸航运卡 [Story]", "其他", "", 0.1f),
    new ItemEntry("GEAR_RosaryA", "神圣念珠 [Story]", "其他", "", 0.1f),
    new ItemEntry("GEAR_SatchelExplosive", "雷管包 [Story]", "其他", "", 0.1f),
    new ItemEntry("GEAR_ScribbledMap", "怡人山谷地图 [Story]", "其他", "", 0.1f),
    new ItemEntry("GEAR_AnalogWatch", "W-指针腕表(TAB) [Watch]", "工具", "", 0.2f),
    new ItemEntry("GEAR_DigitalWatch", "W-电子表(TAB) [Watch]", "工具", "", 0.1f),
    new ItemEntry("GEAR_Stopwatch", "W-秒表(TAB) [Watch]", "工具", "", 0.2f),
    new ItemEntry("GEAR_Sundial", "W-日晷(TAB) [Watch]", "工具", "", 0.5f),
    new ItemEntry("GEAR_BariumCarbonate", "碳酸钡 [WildFire]", "材料", "", 0.15f),
    new ItemEntry("GEAR_CalciumChloride", "氯化钙 [WildFire]", "材料", "", 0.5f),
    new ItemEntry("GEAR_CopperCarbonate", "碳酸铜 [WildFire]", "材料", "", 0.25f),
    new ItemEntry("GEAR_IronFilings", "一把铁屑 [WildFire]", "材料", "", 0.05f),
    new ItemEntry("GEAR_MagnesiumPowder", "镁粉 [WildFire]", "材料", "", 0.1f),
    new ItemEntry("GEAR_Rubidium", "铷 [WildFire]", "材料", "", 0.1f),
    new ItemEntry("GEAR_WolfScarf", "狼皮围巾(自改) [Wolf]", "衣物", "", 0.6f),
    new ItemEntry("GEAR_Candle", "蜡烛 [Candle]", "材料", "", 0.4f),
    new ItemEntry("GEAR_FatRaw", "动物脂肪 [Candle]", "材料", "", 0.3f),
    new ItemEntry("GEAR_Wax", "动物油脂 [Candle]", "食物", "", 0.1f, 50),
    new ItemEntry("GEAR_Wick", "烛心 [Candle]", "材料", "", 0.05f),
    new ItemEntry("GEAR_PillowDZ01", "垫子 [Cushion]", "工具", "", 0.1f),
    new ItemEntry("GEAR_PillowDZ02", "垫子 [Cushion]", "工具", "", 0.1f),
    new ItemEntry("GEAR_PillowDZ03", "垫子 [Cushion]", "工具", "", 0.1f),
    new ItemEntry("GEAR_PillowDZ04", "垫子 [Cushion]", "工具", "", 0.1f),
    new ItemEntry("GEAR_PillowDZ05", "垫子 [Cushion]", "工具", "", 0.1f),
    new ItemEntry("GEAR_PillowDZ06", "垫子 [Cushion]", "工具", "", 0.1f),
    new ItemEntry("GEAR_PillowDZ07", "垫子 [Cushion]", "工具", "", 0.1f),
    new ItemEntry("GEAR_PillowDZ08", "垫子 [Cushion]", "工具", "", 0.1f),
    new ItemEntry("GEAR_PillowDZ09", "垫子 [Cushion]", "工具", "", 0.1f),
    new ItemEntry("GEAR_PillowDZ10", "垫子 [Cushion]", "工具", "", 0.1f),
    new ItemEntry("GEAR_PillowDZ11", "垫子 [Cushion]", "工具", "", 0.1f),
    new ItemEntry("GEAR_PillowDZ12", "垫子 [Cushion]", "工具", "", 0.1f),
    new ItemEntry("GEAR_PillowDZ13", "垫子 [Cushion]", "工具", "", 0.1f),
    new ItemEntry("GEAR_PillowDZ14", "垫子 [Cushion]", "工具", "", 0.1f),
    };
}
