using System.Collections.Generic;

namespace TldHacks;

public class ItemEntry
{
    public string PrefabName;
    public string Name;
    public string Category;
    public float Weight;
    public int Calories;
    public string Remark;

    public ItemEntry(string prefab, string name, string category, string icon, float weight, int calories = 0, string remark = "")
    {
        PrefabName = prefab;
        Name = name;
        Category = category;
        Weight = weight;
        Calories = calories;
        Remark = remark;
    }
}

internal static class ItemDatabase
{
    public static readonly List<ItemEntry> All = new List<ItemEntry>
    {
    new ItemEntry("GEAR_Acorn", "橡子", "食物", "", 0.1f, 75),
    new ItemEntry("GEAR_AcornCoffeeCup", "橡子咖啡(杯)", "食物", "", 0.2f, 30),
    new ItemEntry("GEAR_AcornCooked", "烤橡子", "食物", "", 0.1f, 100),
    new ItemEntry("GEAR_AcornCookedBig", "烤橡子(大)", "食物", "", 0.2f, 175),
    new ItemEntry("GEAR_AcornGrounds", "橡子粉末", "食物", "", 0.05f, 20),
    new ItemEntry("GEAR_AcornShelled", "去壳橡子", "食物", "", 0.08f, 85),
    new ItemEntry("GEAR_AcornShelledBig", "去壳橡子(大)", "食物", "", 0.15f, 160),
    new ItemEntry("GEAR_BeefJerky", "牛肉干", "食物", "", 0.1f, 350),
    new ItemEntry("GEAR_BirchbarkTea", "桦树皮茶", "食物", "", 0.2f),
    new ItemEntry("GEAR_Burdock", "牛蒡根(生)", "食物", "", 0.1f, 50),
    new ItemEntry("GEAR_BurdockPrepared", "牛蒡根(腌制)", "食物", "", 0.1f, 150),
    new ItemEntry("GEAR_BurdockTea", "牛蒡茶", "食物", "", 0.2f),
    new ItemEntry("GEAR_CandyBar", "巧克力棒", "食物", "", 0.1f, 250),
    new ItemEntry("GEAR_CannedBeans", "罐装豆类", "食物", "", 0.5f, 500),
    new ItemEntry("GEAR_CannedSardines", "罐装沙丁鱼", "食物", "", 0.3f, 300),
    new ItemEntry("GEAR_CoffeeCup", "咖啡(杯)", "食物", "", 0.2f),
    new ItemEntry("GEAR_CoffeeTin", "咖啡罐", "食物", "", 0.5f),
    new ItemEntry("GEAR_CondensedMilk", "炼乳", "食物", "", 0.3f, 350),
    new ItemEntry("GEAR_CookedBurbot", "熟江鳕", "食物", "", 0.3f, 400),
    new ItemEntry("GEAR_CookedCohoSalmon", "熟银鲑", "食物", "", 0.4f, 500),
    new ItemEntry("GEAR_CookedGoldeye", "熟金眼鱼", "食物", "", 0.2f, 300),
    new ItemEntry("GEAR_CookedLakeWhiteFish", "熟湖白鱼", "食物", "", 0.3f, 350),
    new ItemEntry("GEAR_CookedMeatBear", "熟熊肉", "食物", "", 0.5f, 500),
    new ItemEntry("GEAR_CookedMeatDeer", "熟鹿肉", "食物", "", 0.5f, 450),
    new ItemEntry("GEAR_CookedMeatRabbit", "熟兔肉", "食物", "", 0.3f, 350),
    new ItemEntry("GEAR_CookedMeatWolf", "熟狼肉", "食物", "", 0.5f, 450),
    new ItemEntry("GEAR_CookedRainbowTrout", "熟虹鳟", "食物", "", 0.3f, 400),
    new ItemEntry("GEAR_CookedRedIrishLord", "熟红爱尔兰鳚", "食物", "", 0.3f, 350),
    new ItemEntry("GEAR_CookedRockfish", "熟岩鱼", "食物", "", 0.3f, 350),
    new ItemEntry("GEAR_CookedSmallMouthBass", "熟小口鲈", "食物", "", 0.3f, 350),
    new ItemEntry("GEAR_DogFood", "狗粮", "食物", "", 0.5f, 400),
    new ItemEntry("GEAR_EnergyBar", "能量棒", "食物", "", 0.1f, 300),
    new ItemEntry("GEAR_GranolaBar", "格兰诺拉棒", "食物", "", 0.1f, 250),
    new ItemEntry("GEAR_GreenTeaCup", "绿茶(杯)", "食物", "", 0.2f),
    new ItemEntry("GEAR_GreenTeaPackage", "绿茶(包)", "食物", "", 0.1f),
    new ItemEntry("GEAR_KetchupChips", "番茄酱薯片", "食物", "", 0.1f, 200),
    new ItemEntry("GEAR_MRE", "军用口粮", "食物", "", 0.5f, 600),
    new ItemEntry("GEAR_MapleSyrup", "枫糖浆", "食物", "", 0.5f, 350),
    new ItemEntry("GEAR_OldMansBeardDressing", "老人须敷料", "食物", "", 0.1f),
    new ItemEntry("GEAR_OldMansBeardHarvested", "老人须(采集)", "食物", "", 0.05f),
    new ItemEntry("GEAR_PeanutButter", "花生酱", "食物", "", 0.5f, 450),
    new ItemEntry("GEAR_PinnacleCanPeaches", "顶峰桃子罐头", "食物", "", 0.5f, 450),
    new ItemEntry("GEAR_RawBurbot", "生江鳕", "食物", "", 0.3f),
    new ItemEntry("GEAR_RawCohoSalmon", "生银鲑", "食物", "", 0.4f),
    new ItemEntry("GEAR_RawGoldeye", "生金眼鱼", "食物", "", 0.2f),
    new ItemEntry("GEAR_RawLakeWhiteFish", "生湖白鱼", "食物", "", 0.3f),
    new ItemEntry("GEAR_RawMeatBear", "生熊肉", "食物", "", 0.5f),
    new ItemEntry("GEAR_RawMeatDeer", "生鹿肉", "食物", "", 0.5f),
    new ItemEntry("GEAR_RawMeatRabbit", "生兔肉", "食物", "", 0.3f),
    new ItemEntry("GEAR_RawMeatWolf", "生狼肉", "食物", "", 0.5f),
    new ItemEntry("GEAR_RawRainbowTrout", "生虹鳟", "食物", "", 0.3f),
    new ItemEntry("GEAR_RawRedIrishLord", "生红爱尔兰鳚", "食物", "", 0.3f),
    new ItemEntry("GEAR_RawRockfish", "生岩鱼", "食物", "", 0.3f),
    new ItemEntry("GEAR_RawSmallMouthBass", "生小口鲈", "食物", "", 0.3f),
    new ItemEntry("GEAR_ReishiMushroom", "灵芝蘑菇(生)", "食物", "", 0.1f, 20),
    new ItemEntry("GEAR_ReishiPrepared", "灵芝(腌制)", "食物", "", 0.1f, 50),
    new ItemEntry("GEAR_ReishiTea", "灵芝茶", "食物", "", 0.2f),
    new ItemEntry("GEAR_RoseHip", "玫瑰果(生)", "食物", "", 0.02f, 30),
    new ItemEntry("GEAR_RoseHipTea", "玫瑰果茶", "食物", "", 0.2f),
    new ItemEntry("GEAR_RosehipsPrepared", "玫瑰果(腌制)", "食物", "", 0.03f, 50),
    new ItemEntry("GEAR_Soda", "汽水", "食物", "", 0.5f, 150),
    new ItemEntry("GEAR_SodaEnergy", "能量饮料", "食物", "", 0.5f, 100),
    new ItemEntry("GEAR_SodaGrape", "葡萄汽水", "食物", "", 0.5f, 150),
    new ItemEntry("GEAR_SodaOrange", "橙子汽水", "食物", "", 0.5f, 150),
    new ItemEntry("GEAR_TomatoSoupCan", "番茄汤罐头", "食物", "", 0.5f, 400),
    new ItemEntry("GEAR_Water1000ml", "净水(1L)", "食物", "", 1f),
    new ItemEntry("GEAR_Water500ml", "净水(500ml)", "食物", "", 0.5f),
    new ItemEntry("GEAR_WaterPurificationTablets", "净水片", "食物", "", 0.02f),
    new ItemEntry("GEAR_WaterSupplyNotPotable", "非饮用水", "食物", "", 1f),
    new ItemEntry("GEAR_WaterSupplyPotable", "饮用水", "食物", "", 1f),
    new ItemEntry("GEAR_Carrot", "胡萝卜", "食物", "", 0.1f, 50),
    new ItemEntry("GEAR_RawMeatPtarmigan", "生松鸡肉", "食物", "", 0.3f),
    new ItemEntry("GEAR_CookedMeatPtarmigan", "熟松鸡肉", "食物", "", 0.3f, 350),
    new ItemEntry("GEAR_RawMeatMoose", "生驼鹿肉", "食物", "", 0.5f),
    new ItemEntry("GEAR_CookedMeatMoose", "熟驼鹿肉", "食物", "", 0.5f, 500),
    new ItemEntry("GEAR_CookedBurdock", "熟牛蒡根", "食物", "", 0.1f, 150),
    new ItemEntry("GEAR_AcornCoffeeTin", "橡子咖啡罐", "食物", "", 0.5f),
    new ItemEntry("GEAR_CookedPtarmiganWhole", "烤整只松鸡", "食物", "", 0.5f, 700),
    new ItemEntry("GEAR_RawPtarmiganWhole", "生整只松鸡", "食物", "", 0.6f),
    new ItemEntry("GEAR_CookedMeatCaribou", "熟驯鹿肉", "食物", "", 0.5f, 450),
    new ItemEntry("GEAR_RawMeatCaribou", "生驯鹿肉", "食物", "", 0.5f),
    new ItemEntry("GEAR_CookedCatTailStalk", "熟香蒲茎", "食物", "", 0.1f, 100),
    new ItemEntry("GEAR_CatTailStalk", "香蒲茎", "食物", "", 0.1f, 50),
    new ItemEntry("GEAR_MilkPowder", "奶粉", "食物", "", 0.3f, 300),
    new ItemEntry("GEAR_MilletFlour", "小米粉", "食物", "", 0.3f, 200),
    new ItemEntry("GEAR_WheatFlour", "面粉", "食物", "", 0.3f, 150),
    new ItemEntry("GEAR_OatmealPacket", "燕麦包", "食物", "", 0.1f, 300),
    new ItemEntry("GEAR_BirchbarkTeaDried", "桦树皮(晒干)", "食物", "", 0.05f),
    new ItemEntry("GEAR_Bow", "手工弓", "武器", "", 1f),
    new ItemEntry("GEAR_BowB", "猎弓B", "武器", "", 1f),
    new ItemEntry("GEAR_BowC", "猎弓C", "武器", "", 1f),
    new ItemEntry("GEAR_FlareGun", "信号枪", "武器", "", 1f),
    new ItemEntry("GEAR_Rifle", "步枪", "武器", "", 4f),
    new ItemEntry("GEAR_RifleB", "山地步枪", "武器", "", 4f),
    new ItemEntry("GEAR_RifleC", "步枪C", "武器", "", 4f),
    new ItemEntry("GEAR_Revolver", "左轮手枪", "武器", "", 1.5f),
    new ItemEntry("GEAR_RevolverB", "左轮手枪B", "武器", "", 1.5f),
    new ItemEntry("GEAR_Stone", "石头", "武器", "", 0.5f),
    new ItemEntry("GEAR_ShotgunDouble", "双管霰弹枪", "武器", "", 3.5f),
    new ItemEntry("GEAR_ShotgunSingle", "单管霰弹枪", "武器", "", 3f),
    new ItemEntry("GEAR_Arrow", "箭矢", "弹药", "", 0.1f),
    new ItemEntry("GEAR_ArrowHardened", "硬化箭矢", "弹药", "", 0.1f),
    new ItemEntry("GEAR_ArrowHead", "箭头", "弹药", "", 0.05f),
    new ItemEntry("GEAR_ArrowShaft", "箭杆", "弹药", "", 0.05f),
    new ItemEntry("GEAR_BlueFlare", "蓝色信号棒", "弹药", "", 0.2f),
    new ItemEntry("GEAR_BrokenArrow", "断箭", "弹药", "", 0.08f),
    new ItemEntry("GEAR_BrokenArrowHardened", "断硬化箭", "弹药", "", 0.08f),
    new ItemEntry("GEAR_Bullet", "步枪子弹", "弹药", "", 0.05f),
    new ItemEntry("GEAR_FlareA", "信号棒", "弹药", "", 0.2f),
    new ItemEntry("GEAR_FlareGunAmmoSingle", "信号弹(单发)", "弹药", "", 0.1f),
    new ItemEntry("GEAR_RevolverAmmoBox", "左轮弹药箱", "弹药", "", 0.15f),
    new ItemEntry("GEAR_RevolverAmmoCasing", "左轮弹壳", "弹药", "", 0.02f),
    new ItemEntry("GEAR_RevolverAmmoSingle", "左轮子弹(单发)", "弹药", "", 0.03f),
    new ItemEntry("GEAR_RifleAmmoBox", "步枪弹药箱", "弹药", "", 0.2f),
    new ItemEntry("GEAR_RifleAmmoCasing", "步枪弹壳", "弹药", "", 0.02f),
    new ItemEntry("GEAR_RifleAmmoSingle", "步枪子弹(单发)", "弹药", "", 0.05f),
    new ItemEntry("GEAR_ScrapLead", "铅料", "弹药", "", 0.1f),
    new ItemEntry("GEAR_SprayPaintCan", "喷漆罐", "弹药", "", 0.3f),
    new ItemEntry("GEAR_SprayPaintCanGlyphA", "符文喷漆罐", "弹药", "", 0.3f),
    new ItemEntry("GEAR_ShotgunAmmoSingle", "霰弹枪子弹(单发)", "弹药", "", 0.05f),
    new ItemEntry("GEAR_ShotgunAmmoBox", "霰弹枪弹药箱", "弹药", "", 0.25f),
    new ItemEntry("GEAR_ShotgunAmmoCasing", "霰弹枪弹壳", "弹药", "", 0.02f),
    new ItemEntry("GEAR_SpearFishingHead", "鱼叉头", "弹药", "", 0.1f),
    new ItemEntry("GEAR_BottleAntibiotics", "抗生素", "医疗", "", 0.1f),
    new ItemEntry("GEAR_BottleHydrogenPeroxide", "消毒剂", "医疗", "", 0.2f),
    new ItemEntry("GEAR_BottlePainKillers", "止痛药", "医疗", "", 0.1f),
    new ItemEntry("GEAR_HeavyBandage", "重型绷带", "医疗", "", 0.2f),
    new ItemEntry("GEAR_Bandage", "绷带", "医疗", "", 0.1f),
    new ItemEntry("GEAR_BottleOfWater", "急救水", "医疗", "", 0.5f),
    new ItemEntry("GEAR_AntiInfectionWipes", "消毒湿巾", "医疗", "", 0.05f),
    new ItemEntry("GEAR_StitchingKit", "缝合套件", "医疗", "", 0.1f),
    new ItemEntry("GEAR_BoltCutters", "断线钳", "工具", "", 1.5f),
    new ItemEntry("GEAR_CanOpener", "开罐器", "工具", "", 0.1f),
    new ItemEntry("GEAR_CookingPot", "炊具锅", "工具", "", 1f),
    new ItemEntry("GEAR_Firestriker", "打火石", "工具", "", 0.1f),
    new ItemEntry("GEAR_Flashlight", "手电筒", "工具", "", 0.5f),
    new ItemEntry("GEAR_FishingLureA", "鱼饵A", "工具", "", 0.02f),
    new ItemEntry("GEAR_FishingLureB", "鱼饵B", "工具", "", 0.02f),
    new ItemEntry("GEAR_FishingLureC", "鱼饵C", "工具", "", 0.02f),
    new ItemEntry("GEAR_Hacksaw", "钢锯", "工具", "", 0.8f),
    new ItemEntry("GEAR_Hammer", "锤子", "工具", "", 1f),
    new ItemEntry("GEAR_Hatchet", "短柄斧", "工具", "", 1.5f),
    new ItemEntry("GEAR_HatchetImprovised", "即兴短柄斧", "工具", "", 1.2f),
    new ItemEntry("GEAR_HighQualityTools", "高质工具", "工具", "", 2f),
    new ItemEntry("GEAR_Hook", "鱼钩", "工具", "", 0.01f),
    new ItemEntry("GEAR_HookAndLine", "钩线组合", "工具", "", 0.05f),
    new ItemEntry("GEAR_ImprovisedCrampons", "即兴冰爪", "工具", "", 0.5f),
    new ItemEntry("GEAR_JeremiahKnife", "杰里迈亚的刀", "工具", "", 0.3f),
    new ItemEntry("GEAR_Knife", "猎刀", "工具", "", 0.3f),
    new ItemEntry("GEAR_KnifeImprovised", "即兴刀", "工具", "", 0.3f),
    new ItemEntry("GEAR_KnifeScrapMetal", "废金属刀", "工具", "", 0.3f),
    new ItemEntry("GEAR_Line", "钓鱼线", "工具", "", 0.05f),
    new ItemEntry("GEAR_MagnifyingLens", "放大镜", "工具", "", 0.1f),
    new ItemEntry("GEAR_NoiseMaker", "噪音器", "工具", "", 0.3f),
    new ItemEntry("GEAR_PackMatches", "盒装火柴", "工具", "", 0.05f),
    new ItemEntry("GEAR_Prybar", "撬棍", "工具", "", 1f),
    new ItemEntry("GEAR_RifleCleaningKit", "步枪清洁套件", "工具", "", 0.5f),
    new ItemEntry("GEAR_SewingKit", "针线包", "工具", "", 0.1f),
    new ItemEntry("GEAR_SharpeningStone", "磨刀石", "工具", "", 0.2f),
    new ItemEntry("GEAR_SimpleTools", "简易工具", "工具", "", 1f),
    new ItemEntry("GEAR_Snare", "陷阱", "工具", "", 0.3f),
    new ItemEntry("GEAR_TipUp", "冰钓架", "工具", "", 0.5f),
    new ItemEntry("GEAR_CarBattery", "汽车蓄电池", "工具", "", 5f),
    new ItemEntry("GEAR_Torch", "火把", "工具", "", 0.5f),
    new ItemEntry("GEAR_Vice", "台钳", "工具", "", 5f),
    new ItemEntry("GEAR_WoodMatches", "木质火柴", "工具", "", 0.05f),
    new ItemEntry("GEAR_WoodworkingTools", "木工工具", "工具", "", 2f),
    new ItemEntry("GEAR_KeroseneLamp", "煤油灯", "工具", "", 0.5f),
    new ItemEntry("GEAR_Compass", "指南针", "工具", "", 0.1f),
    new ItemEntry("GEAR_FishingTackleBox", "钓具箱", "工具", "", 0.3f),
    new ItemEntry("GEAR_SpearFishing", "鱼叉", "工具", "", 1.5f),
    new ItemEntry("GEAR_RevolverCleaningKit", "左轮清洁套件", "工具", "", 0.3f),
    new ItemEntry("GEAR_ShotgunCleaningKit", "霰弹枪清洁套件", "工具", "", 0.3f),
    new ItemEntry("GEAR_SafeCrackingStethoscope", "听诊器(开保险箱)", "工具", "", 0.1f),
    new ItemEntry("GEAR_Balaclava", "巴拉克拉瓦头套", "衣物", "", 0.2f),
    new ItemEntry("GEAR_BaseballCap", "棒球帽", "衣物", "", 0.1f),
    new ItemEntry("GEAR_BasicBoots", "基础靴", "衣物", "", 1f),
    new ItemEntry("GEAR_BasicGloves", "基础手套", "衣物", "", 0.2f),
    new ItemEntry("GEAR_BasicShoes", "基础鞋", "衣物", "", 0.5f),
    new ItemEntry("GEAR_BasicWinterCoat", "基础冬装大衣", "衣物", "", 1.5f),
    new ItemEntry("GEAR_BasicWoolHat", "基础羊毛帽", "衣物", "", 0.1f),
    new ItemEntry("GEAR_BasicWoolScarf", "基础羊毛围巾", "衣物", "", 0.1f),
    new ItemEntry("GEAR_BearSkinCoat", "熊皮大衣", "衣物", "", 5f),
    new ItemEntry("GEAR_CargoPants", "工装裤", "衣物", "", 0.8f),
    new ItemEntry("GEAR_ClimbingSocks", "攀岩袜", "衣物", "", 0.1f),
    new ItemEntry("GEAR_CombatBoots", "战斗靴", "衣物", "", 1.5f),
    new ItemEntry("GEAR_CombatPants", "战斗裤", "衣物", "", 1f),
    new ItemEntry("GEAR_CottonHoodie", "棉质连帽衫", "衣物", "", 0.5f),
    new ItemEntry("GEAR_CottonScarf", "棉围巾", "衣物", "", 0.1f),
    new ItemEntry("GEAR_CottonShirt", "棉衬衫", "衣物", "", 0.3f),
    new ItemEntry("GEAR_DeerSkinBoots", "鹿皮靴", "衣物", "", 1f),
    new ItemEntry("GEAR_DeerSkinPants", "鹿皮裤", "衣物", "", 1.5f),
    new ItemEntry("GEAR_DownVest", "羽绒背心", "衣物", "", 0.5f),
    new ItemEntry("GEAR_EarMuffs", "耳罩", "衣物", "", 0.2f),
    new ItemEntry("GEAR_FleeceMittens", "抓绒连指手套", "衣物", "", 0.2f),
    new ItemEntry("GEAR_FleeceSweater", "抓绒毛衣", "衣物", "", 0.5f),
    new ItemEntry("GEAR_Gauntlets", "重型手套", "衣物", "", 0.5f),
    new ItemEntry("GEAR_HeavyWoolSweater", "厚羊毛毛衣", "衣物", "", 1f),
    new ItemEntry("GEAR_ImprovisedHat", "即兴帽子", "衣物", "", 0.3f),
    new ItemEntry("GEAR_ImprovisedMittens", "即兴连指手套", "衣物", "", 0.3f),
    new ItemEntry("GEAR_InsulatedPants", "保暖裤", "衣物", "", 1f),
    new ItemEntry("GEAR_InsulatedVest", "保暖背心", "衣物", "", 0.8f),
    new ItemEntry("GEAR_Jeans", "牛仔裤", "衣物", "", 0.7f),
    new ItemEntry("GEAR_LeatherShoes", "皮鞋", "衣物", "", 0.8f),
    new ItemEntry("GEAR_LightParka", "轻便派克大衣", "衣物", "", 1.5f),
    new ItemEntry("GEAR_LongUnderwear", "长内衣", "衣物", "", 0.4f),
    new ItemEntry("GEAR_LongUnderwearWool", "羊毛长内衣", "衣物", "", 0.5f),
    new ItemEntry("GEAR_Mittens", "羊毛连指手套", "衣物", "", 0.2f),
    new ItemEntry("GEAR_MooseHideBag", "驼鹿皮袋", "衣物", "", 1f),
    new ItemEntry("GEAR_MooseHideCloak", "驼鹿皮斗篷", "衣物", "", 4f),
    new ItemEntry("GEAR_PlaidShirt", "格子衬衫", "衣物", "", 0.4f),
    new ItemEntry("GEAR_RabbitSkinMittens", "兔皮连指手套", "衣物", "", 0.3f),
    new ItemEntry("GEAR_RabbitskinHat", "兔皮帽", "衣物", "", 0.3f),
    new ItemEntry("GEAR_SkiGloves", "滑雪手套", "衣物", "", 0.3f),
    new ItemEntry("GEAR_SkiJacket", "滑雪夹克", "衣物", "", 1.5f),
    new ItemEntry("GEAR_TeeShirt", "T恤", "衣物", "", 0.2f),
    new ItemEntry("GEAR_Toque", "无边帽", "衣物", "", 0.1f),
    new ItemEntry("GEAR_WolfSkinCape", "狼皮披风", "衣物", "", 3f),
    new ItemEntry("GEAR_WorkBoots", "工作靴", "衣物", "", 1.5f),
    new ItemEntry("GEAR_WorkGloves", "工作手套", "衣物", "", 0.2f),
    new ItemEntry("GEAR_WorkPants", "工作裤", "衣物", "", 0.8f),
    new ItemEntry("GEAR_WoolSocks", "羊毛袜", "衣物", "", 0.1f),
    new ItemEntry("GEAR_WoolSweater", "羊毛毛衣", "衣物", "", 0.8f),
    new ItemEntry("GEAR_WoolWrap", "羊毛面罩", "衣物", "", 0.2f),
    new ItemEntry("GEAR_WoolWrapCap", "羊毛面罩帽", "衣物", "", 0.2f),
    new ItemEntry("GEAR_ArmWrap", "手臂绑带", "衣物", "", 0.1f),
    new ItemEntry("GEAR_LeatherBindings", "皮革绑腿", "衣物", "", 0.2f),
    new ItemEntry("GEAR_MackinawJacket", "麦金纳克夹克", "衣物", "", 1.5f),
    new ItemEntry("GEAR_PrisonerVest", "囚犯背心", "衣物", "", 0.3f),
    new ItemEntry("GEAR_SurvivorParka", "幸存者派克大衣", "衣物", "", 2f),
    new ItemEntry("GEAR_WolfskinParka", "狼皮派克大衣", "衣物", "", 2.5f),
    new ItemEntry("GEAR_ColdFusionSuit", "极寒防护套装", "衣物", "", 3f),
    new ItemEntry("GEAR_HeavyParka", "厚派克大衣", "衣物", "", 2.5f),
    new ItemEntry("GEAR_TacticalGloves", "战术手套", "衣物", "", 0.3f),
    new ItemEntry("GEAR_TacticalJacket", "战术夹克", "衣物", "", 2f),
    new ItemEntry("GEAR_ExpeditionCoat", "远征风雪大衣", "衣物", "", 2.5f),
    new ItemEntry("GEAR_ExpeditionParka", "远征派克大衣", "衣物", "", 2.5f),
    new ItemEntry("GEAR_Accelerant", "引火剂", "材料", "", 0.1f),
    new ItemEntry("GEAR_AccelerantGunpowder", "火药引火剂", "材料", "", 0.1f),
    new ItemEntry("GEAR_AccelerantKerosene", "煤油引火剂", "材料", "", 0.1f),
    new ItemEntry("GEAR_BarkTinder", "树皮火绒", "材料", "", 0.05f),
    new ItemEntry("GEAR_BearHide", "熊皮(生)", "材料", "", 5f),
    new ItemEntry("GEAR_BearHideDried", "熊皮(晒干)", "材料", "", 3f),
    new ItemEntry("GEAR_BearQuarter", "熊肉块", "材料", "", 4f),
    new ItemEntry("GEAR_BearSkinBedRoll", "熊皮睡袋", "材料", "", 2.5f),
    new ItemEntry("GEAR_BirchSaplingDried", "桦树苗(晒干)", "材料", "", 0.2f),
    new ItemEntry("GEAR_BirchbarkPrepared", "桦树皮(处理过)", "材料", "", 0.1f),
    new ItemEntry("GEAR_Charcoal", "木炭", "材料", "", 0.02f),
    new ItemEntry("GEAR_Coal", "煤炭", "材料", "", 1f),
    new ItemEntry("GEAR_Cloth", "布料", "材料", "", 0.1f),
    new ItemEntry("GEAR_CrowFeather", "乌鸦羽毛", "材料", "", 0.01f),
    new ItemEntry("GEAR_PtarmiganFeather", "松鸡羽绒", "材料", "", 0.01f),
    new ItemEntry("GEAR_DustingSulfur", "硫磺粉", "材料", "", 0.1f),
    new ItemEntry("GEAR_Firelog", "薪柴", "材料", "", 1.5f),
    new ItemEntry("GEAR_GunpowderCan", "火药罐", "材料", "", 0.3f),
    new ItemEntry("GEAR_Gut", "肠线(生)", "材料", "", 0.1f),
    new ItemEntry("GEAR_GutDried", "肠线(晒干)", "材料", "", 0.05f),
    new ItemEntry("GEAR_Hardwood", "硬木", "材料", "", 1f),
    new ItemEntry("GEAR_LampFuel", "灯油", "材料", "", 0.5f),
    new ItemEntry("GEAR_LeatherDried", "皮革(晒干)", "材料", "", 0.3f),
    new ItemEntry("GEAR_LeatherHide", "皮革(生)", "材料", "", 0.5f),
    new ItemEntry("GEAR_LeatherHideDried", "皮革毛皮(晒干)", "材料", "", 0.3f),
    new ItemEntry("GEAR_MapleSaplingDried", "枫树苗(晒干)", "材料", "", 0.2f),
    new ItemEntry("GEAR_MooseHideDried", "驼鹿皮(晒干)", "材料", "", 2f),
    new ItemEntry("GEAR_Newsprint", "报纸", "材料", "", 0.05f),
    new ItemEntry("GEAR_NewsprintRoll", "报纸卷", "材料", "", 0.1f),
    new ItemEntry("GEAR_PaperStack", "纸堆", "材料", "", 0.2f),
    new ItemEntry("GEAR_RabbitCarcass", "兔子尸体", "材料", "", 0.5f),
    new ItemEntry("GEAR_RabbitPelt", "兔皮(生)", "材料", "", 0.3f),
    new ItemEntry("GEAR_RabbitPeltDried", "兔皮(晒干)", "材料", "", 0.15f),
    new ItemEntry("GEAR_ReclaimedWoodB", "回收木材", "材料", "", 0.5f),
    new ItemEntry("GEAR_RecycledCan", "回收铁罐", "材料", "", 0.1f),
    new ItemEntry("GEAR_ScrapMetal", "废金属", "材料", "", 0.5f),
    new ItemEntry("GEAR_Softwood", "软木", "材料", "", 0.5f),
    new ItemEntry("GEAR_SpearHead", "矛头", "材料", "", 0.3f),
    new ItemEntry("GEAR_StagQuarter", "雄鹿肉块", "材料", "", 4f),
    new ItemEntry("GEAR_Stick", "树枝", "材料", "", 0.1f),
    new ItemEntry("GEAR_StumpRemover", "树桩去除剂", "材料", "", 0.3f),
    new ItemEntry("GEAR_Tinder", "火绒", "材料", "", 0.05f),
    new ItemEntry("GEAR_WolfCarcass", "狼尸体", "材料", "", 8f),
    new ItemEntry("GEAR_WolfPelt", "狼皮(生)", "材料", "", 2f),
    new ItemEntry("GEAR_WolfPeltDried", "狼皮(晒干)", "材料", "", 1f),
    new ItemEntry("GEAR_WolfQuarter", "狼肉块", "材料", "", 3f),
    new ItemEntry("GEAR_Potato", "土豆", "食物", "", 0.2f, 50),
    new ItemEntry("GEAR_BoneB", "骨头", "材料", "", 0.2f),
    new ItemEntry("GEAR_BoneBearB", "熊骨头", "材料", "", 0.5f),
    new ItemEntry("GEAR_BoneDeerB", "鹿骨头", "材料", "", 0.3f),
    new ItemEntry("GEAR_BoneWolfB", "狼骨头", "材料", "", 0.3f),
    new ItemEntry("GEAR_BoneMooseB", "驼鹿骨头", "材料", "", 0.5f),
    new ItemEntry("GEAR_MooseQuarter", "驼鹿肉块", "材料", "", 4f),
    new ItemEntry("GEAR_PtarmiganCarcass", "松鸡尸体", "材料", "", 0.5f),
    new ItemEntry("GEAR_PtarmiganPelt", "松鸡皮", "材料", "", 0.1f),
    new ItemEntry("GEAR_CaribouHide", "驯鹿皮(生)", "材料", "", 2f),
    new ItemEntry("GEAR_CaribouHideDried", "驯鹿皮(晒干)", "材料", "", 1.5f),
    new ItemEntry("GEAR_CuredLeather", "鞣制皮革", "材料", "", 0.3f),
    new ItemEntry("GEAR_ForgedKnifeBladeA", "锻造刀刃A", "材料", "", 0.3f),
    new ItemEntry("GEAR_ForgedKnifeBladeB", "锻造刀刃B", "材料", "", 0.3f),
    new ItemEntry("GEAR_ForgedHatchetHead", "锻造斧头", "材料", "", 0.5f),
    new ItemEntry("GEAR_SurvivalBow", "生存弓", "材料", "", 1f),
    new ItemEntry("GEAR_WolfCarcassMoose", "驼鹿皮革碎片", "材料", "", 1f),
    new ItemEntry("GEAR_OldWoolScarf", "旧羊毛围巾", "材料", "", 0.1f),
    new ItemEntry("GEAR_Rifle_Barbs", "巴尔布的步枪", "DLC武器", "", 4f, 0, "沿海公路，略重"),
    new ItemEntry("GEAR_Rifle_Vaughns", "沃恩的步枪", "DLC武器", "", 4f, 0, "神秘湖，极轻"),
    new ItemEntry("GEAR_Rifle_Curators", "管理人的步枪", "DLC武器", "", 4f, 0, "灰烬峡谷，金饰"),
    new ItemEntry("GEAR_Bow_Sports", "运动弓", "DLC武器", "", 1f, 0, "废弃机场，最轻"),
    new ItemEntry("GEAR_Bow_Woodwrights", "木匠的弓", "DLC武器", "", 1f, 0, "寂静河谷，最重最稳"),
    new ItemEntry("GEAR_RevolverFancy", "猎人的左轮", "DLC武器", "", 1.5f, 0, "远程伤害更高"),
    new ItemEntry("GEAR_RevolverGreen", "护林人的左轮", "DLC武器", "", 1.5f, 0, "绿色涂装"),
    new ItemEntry("GEAR_RevolverStubNosed", "典狱长的左轮", "DLC武器", "", 1.5f, 0, "短管，近距离强"),
    new ItemEntry("GEAR_Knife_Hunter", "狩猎刀（传奇）", "DLC武器", "", 0.3f, 0, "更快剥皮，高耐久"),
    new ItemEntry("GEAR_Hatchet_Crafted", "手斧（传奇）", "DLC武器", "", 1f, 0, "锻造版，效率更高"),
    new ItemEntry("GEAR_BearSpear", "猎熊矛", "DLC武器", "", 2.5f, 0, "剧情DLC专属，可击杀熊"),
    new ItemEntry("GEAR_BearSpearBroken", "损坏的猎熊矛", "DLC武器", "", 2f),
    new ItemEntry("GEAR_BookA", "书 A", "其他", "", 0.5f),
    new ItemEntry("GEAR_BookB", "书 B", "其他", "", 0.5f),
    new ItemEntry("GEAR_BookBopen", "书 B(翻开)", "其他", "", 0.5f),
    new ItemEntry("GEAR_BookC", "书 C", "其他", "", 0.5f),
    new ItemEntry("GEAR_BookD", "书 D", "其他", "", 0.5f),
    new ItemEntry("GEAR_BookE", "书 E", "其他", "", 0.5f),
    new ItemEntry("GEAR_BookEopen", "书 E(翻开)", "其他", "", 0.5f),
    new ItemEntry("GEAR_BookF", "书 F", "其他", "", 0.5f),
    new ItemEntry("GEAR_BookFopen", "书 F(翻开)", "其他", "", 0.5f),
    new ItemEntry("GEAR_BookG", "书 G", "其他", "", 0.5f),
    new ItemEntry("GEAR_BookH", "书 H", "其他", "", 0.5f),
    new ItemEntry("GEAR_BookHopen", "书 H(翻开)", "其他", "", 0.5f),
    new ItemEntry("GEAR_BookI", "书 I", "其他", "", 0.5f),
    new ItemEntry("GEAR_BookLabE_01", "实验室书籍01", "其他", "", 0.5f),
    new ItemEntry("GEAR_BookLabE_02", "实验室书籍02", "其他", "", 0.5f),
    new ItemEntry("GEAR_BookLabE_03", "实验室书籍03", "其他", "", 0.5f),
    new ItemEntry("GEAR_BookLabE_Open_01", "实验室书籍(翻开)01", "其他", "", 0.5f),
    new ItemEntry("GEAR_BookManual", "手册", "其他", "", 0.5f),
    new ItemEntry("GEAR_BlackrockCodeNote", "黑岩密码纸条", "其他", "", 0.05f),
    new ItemEntry("GEAR_DarkwalkerDiary1", "黑暗行者日记1", "其他", "", 0.05f),
    new ItemEntry("GEAR_DarkwalkerDiary2", "黑暗行者日记2", "其他", "", 0.05f),
    new ItemEntry("GEAR_DarkwalkerDiary3", "黑暗行者日记3", "其他", "", 0.05f),
    new ItemEntry("GEAR_DarkwalkerDiary4", "黑暗行者日记4", "其他", "", 0.05f),
    new ItemEntry("GEAR_DarkwalkerDiary5", "黑暗行者日记5", "其他", "", 0.05f),
    new ItemEntry("GEAR_DarkwalkerDiary6", "黑暗行者日记6", "其他", "", 0.05f),
    new ItemEntry("GEAR_DarkwalkerDiary7", "黑暗行者日记7", "其他", "", 0.05f),
    new ItemEntry("GEAR_DarkwalkerDiary8", "黑暗行者日记8", "其他", "", 0.05f),
    new ItemEntry("GEAR_DarkwalkerDiary9", "黑暗行者日记9", "其他", "", 0.05f),
    new ItemEntry("GEAR_DarkwalkerDiary10", "黑暗行者日记10", "其他", "", 0.05f),
    new ItemEntry("GEAR_DeadmanNote1", "死人笔记1", "其他", "", 0.05f),
    new ItemEntry("GEAR_DeadmanNote2", "死人笔记2", "其他", "", 0.05f),
    new ItemEntry("GEAR_DeadmanNote3", "死人笔记3", "其他", "", 0.05f),
    new ItemEntry("GEAR_DeadmanNote4", "死人笔记4", "其他", "", 0.05f),
    new ItemEntry("GEAR_DeadmanNote5", "死人笔记5", "其他", "", 0.05f),
    new ItemEntry("GEAR_VisorNoteBlackrock2", "眼镜笔记-黑岩2", "其他", "", 0.05f),
    new ItemEntry("GEAR_VisorNoteCH1", "眼镜笔记-CH1", "其他", "", 0.05f),
    new ItemEntry("GEAR_VisorNoteCH2", "眼镜笔记-CH2", "其他", "", 0.05f),
    new ItemEntry("GEAR_VisorNoteFM1", "眼镜笔记-FM1", "其他", "", 0.05f),
    new ItemEntry("GEAR_VisorNoteFM2", "眼镜笔记-FM2", "其他", "", 0.05f),
    new ItemEntry("GEAR_VisorNoteHRV2", "眼镜笔记-HRV2", "其他", "", 0.05f),
    new ItemEntry("GEAR_VisorNoteMT3", "眼镜笔记-MT3", "其他", "", 0.05f),
    new ItemEntry("GEAR_VisorNotePV1", "眼镜笔记-PV1", "其他", "", 0.05f),
    new ItemEntry("GEAR_VisorNotePV3", "眼镜笔记-PV3", "其他", "", 0.05f),
    new ItemEntry("GEAR_BedRoll", "睡袋", "其他", "", 1f),
    new ItemEntry("GEAR_Placeholder", "占位物品", "其他", "", 0.1f),
    };

    // 分类顺序,给 UI 用
    public static readonly string[] Categories = { "全部", "食物", "工具", "武器", "弹药", "医疗", "衣物", "材料", "DLC武器", "其他" };
}
