using System.Collections.Generic;

namespace TldHacks;

public class ItemEntry
{
    public string PrefabName;
    public string Name;
    public string Category;
    public float Weight;
    public int Calories;
    public string Remark;
    public bool IsValid = true;
    public bool IsMod;
    public string NameZh;
    public string NameEn;
    // v6.6 GC: 预缓存带卡路里后缀的显示名,避免 Spawner UI 每帧字符串拼接
    public string DisplayLabelZh;
    public string DisplayLabelEn;

    public ItemEntry(string prefab, string name, string category, string icon, float weight, int calories = 0, string remark = "")
    {
        PrefabName = prefab;
        Name = name;
        Category = category;
        Weight = weight;
        Calories = calories;
        Remark = remark;
    }
}

internal static class ItemDatabase
{
    public static readonly List<ItemEntry> All = new List<ItemEntry>
    {
    new ItemEntry("GEAR_Acorn", "橡实", "食物", "", 0.1f, 75),
    new ItemEntry("GEAR_AcornCoffeeCup", "一杯橡实咖啡", "饮料", "", 0.2f, 30),
    new ItemEntry("GEAR_AcornCooked", "橡实（熟）", "食物", "", 0.1f, 100),
    new ItemEntry("GEAR_AcornCookedBig", "橡实（熟 - 大份）", "食物", "", 0.2f, 175),
    new ItemEntry("GEAR_AcornGrounds", "橡实渣", "食物", "", 0.05f, 20),
    new ItemEntry("GEAR_AcornShelled", "制好的橡实", "食物", "", 0.08f, 85),
    new ItemEntry("GEAR_AcornShelledBig", "制好的橡实（大份）", "食物", "", 0.15f, 160),
    new ItemEntry("GEAR_BeefJerky", "牛肉干", "食物", "", 0.1f, 350),
    new ItemEntry("GEAR_BirchbarkTea", "桦树皮茶", "饮料", "", 0.2f),
    new ItemEntry("GEAR_Burdock", "牛蒡根", "食物", "", 0.1f, 50),
    new ItemEntry("GEAR_BurdockPrepared", "加工过的牛蒡", "食物", "", 0.1f, 150),
    new ItemEntry("GEAR_BurdockTea", "牛蒡茶", "饮料", "", 0.2f),
    new ItemEntry("GEAR_CandyBar", "糖棒", "食物", "", 0.1f, 250),
    new ItemEntry("GEAR_CannedBeans", "罐装豆类", "食物", "", 0.5f, 500),
    new ItemEntry("GEAR_CannedSardines", "罐装沙丁鱼", "食物", "", 0.3f, 300),
    new ItemEntry("GEAR_CoffeeCup", "一杯咖啡", "饮料", "", 0.2f),
    new ItemEntry("GEAR_CoffeeTin", "咖啡罐", "饮料", "", 0.5f),
    new ItemEntry("GEAR_CondensedMilk", "炼乳", "食物", "", 0.3f, 350),
    new ItemEntry("GEAR_CookedBurbot", "淡水鳕鱼 (熟)", "食物", "", 0.3f, 400),
    new ItemEntry("GEAR_CookedCohoSalmon", "银大马哈鱼 (熟)", "食物", "", 0.4f, 500),
    new ItemEntry("GEAR_CookedGoldeye", "金目鱼 (熟)", "食物", "", 0.2f, 300),
    new ItemEntry("GEAR_CookedLakeWhiteFish", "湖白鲑 (熟)", "食物", "", 0.3f, 350),
    new ItemEntry("GEAR_CookedMeatBear", "熟熊肉", "食物", "", 0.5f, 500),
    new ItemEntry("GEAR_CookedMeatCougar", "美洲狮肉（熟）", "食物", "", 0.5f, 500),
    new ItemEntry("GEAR_CookedMeatDeer", "熟鹿肉", "食物", "", 0.5f, 450),
    new ItemEntry("GEAR_CookedMeatRabbit", "熟兔肉", "食物", "", 0.3f, 350),
    new ItemEntry("GEAR_CookedMeatWolf", "熟狼肉", "食物", "", 0.5f, 450),
    new ItemEntry("GEAR_CookedRainbowTrout", "虹鳟鱼 (熟)", "食物", "", 0.3f, 400),
    new ItemEntry("GEAR_CookedRedIrishLord", "爱尔兰王鱼 (熟)", "食物", "", 0.3f, 350),
    new ItemEntry("GEAR_CookedRockfish", "岩鱼 (熟)", "食物", "", 0.3f, 350),
    new ItemEntry("GEAR_CookedSmallMouthBass", "小嘴鲈鱼 (熟)", "食物", "", 0.3f, 350),
    new ItemEntry("GEAR_DogFood", "狗粮", "食物", "", 0.5f, 400),
    new ItemEntry("GEAR_EnergyBar", "能量棒", "食物", "", 0.1f, 300),
    new ItemEntry("GEAR_GranolaBar", "格兰诺拉燕麦卷", "食物", "", 0.1f, 250),
    new ItemEntry("GEAR_GreenTeaCup", "一杯花茶", "饮料", "", 0.2f),
    new ItemEntry("GEAR_GreenTeaPackage", "花茶", "饮料", "", 0.1f),
    new ItemEntry("GEAR_KetchupChips", "番茄酱薯条", "食物", "", 0.1f, 200),
    new ItemEntry("GEAR_MRE", "军用口粮", "食物", "", 0.5f, 600),
    new ItemEntry("GEAR_MapleSyrup", "枫糖糖浆", "食物", "", 0.5f, 350),
    new ItemEntry("GEAR_OldMansBeardDressing", "胡须地衣伤口敷料", "食物", "", 0.1f),
    new ItemEntry("GEAR_OldMansBeardHarvested", "老人须(采集)", "食物", "", 0.05f),
    new ItemEntry("GEAR_PeanutButter", "花生酱", "食物", "", 0.5f, 450),
    new ItemEntry("GEAR_PinnacleCanPeaches", "顶峰桃子罐头", "食物", "", 0.5f, 450),
    new ItemEntry("GEAR_RawBurbot", "淡水鳕鱼 (生)", "食物", "", 0.3f),
    new ItemEntry("GEAR_RawCohoSalmon", "银大马哈鱼 (生)", "食物", "", 0.4f),
    new ItemEntry("GEAR_RawGoldeye", "金目鱼 (生)", "食物", "", 0.2f),
    new ItemEntry("GEAR_RawLakeWhiteFish", "湖白鲑 (生)", "食物", "", 0.3f),
    new ItemEntry("GEAR_RawMeatBear", "生熊肉", "食物", "", 0.5f),
    new ItemEntry("GEAR_RawMeatDeer", "生鹿肉", "食物", "", 0.5f),
    new ItemEntry("GEAR_RawMeatRabbit", "生兔肉", "食物", "", 0.3f),
    new ItemEntry("GEAR_RawMeatWolf", "生狼肉", "食物", "", 0.5f),
    new ItemEntry("GEAR_RawRainbowTrout", "虹鳟鱼 (生)", "食物", "", 0.3f),
    new ItemEntry("GEAR_RawRedIrishLord", "爱尔兰王鱼 (生)", "食物", "", 0.3f),
    new ItemEntry("GEAR_RawRockfish", "岩鱼 (生)", "食物", "", 0.3f),
    new ItemEntry("GEAR_RawSmallMouthBass", "小嘴鲈鱼 (生)", "食物", "", 0.3f),
    new ItemEntry("GEAR_ReishiMushroom", "灵芝", "食物", "", 0.1f, 20),
    new ItemEntry("GEAR_ReishiPrepared", "灵芝(腌制)", "食物", "", 0.1f, 50),
    new ItemEntry("GEAR_ReishiTea", "灵芝茶", "饮料", "", 0.2f),
    new ItemEntry("GEAR_RoseHip", "玫瑰果", "食物", "", 0.02f, 30),
    new ItemEntry("GEAR_RoseHipTea", "玫瑰茶", "饮料", "", 0.2f),
    new ItemEntry("GEAR_RosehipsPrepared", "玫瑰果(腌制)", "食物", "", 0.03f, 50),
    new ItemEntry("GEAR_Soda", "汽水", "饮料", "", 0.5f, 150),
    new ItemEntry("GEAR_SodaEnergy", "动起来！能量饮料", "饮料", "", 0.5f, 100),
    new ItemEntry("GEAR_SodaGrape", "葡萄汽水", "饮料", "", 0.5f, 150),
    new ItemEntry("GEAR_SodaOrange", "橙子汽水", "饮料", "", 0.5f, 150),
    new ItemEntry("GEAR_TomatoSoupCan", "番茄汤", "食物", "", 0.5f, 400),
    new ItemEntry("GEAR_Water1000ml", "净水(1L)", "饮料", "", 1f),
    new ItemEntry("GEAR_Water500ml", "净水(500ml)", "饮料", "", 0.5f),
    new ItemEntry("GEAR_WaterPurificationTablets", "净水药片", "工具", "", 0.02f),
    new ItemEntry("GEAR_WaterSupplyNotPotable", "非饮用水", "饮料", "", 1f),
    new ItemEntry("GEAR_WaterSupplyPotable", "饮用水", "饮料", "", 1f),
    new ItemEntry("GEAR_Carrot", "胡萝卜", "食物", "", 0.1f, 50),
    new ItemEntry("GEAR_RawMeatPtarmigan", "生松鸡肉", "食物", "", 0.3f),
    new ItemEntry("GEAR_CookedMeatPtarmigan", "熟松鸡肉", "食物", "", 0.3f, 350),
    new ItemEntry("GEAR_CuredMeatPtarmigan", "鸡肉干", "食物", "", 0.3f, 350),
    new ItemEntry("GEAR_SaltedMeatPtarmigan", "腌制的鸡肉", "食物", "", 0.3f, 350),
    new ItemEntry("GEAR_RawMeatCougar", "美洲狮肉（生）", "食物", "", 0.5f),
    new ItemEntry("GEAR_RawMeatMoose", "驼鹿肉", "食物", "", 0.5f),
    new ItemEntry("GEAR_CookedMeatMoose", "驼鹿肉 (熟)", "食物", "", 0.5f, 500),
    new ItemEntry("GEAR_CookedBurdock", "熟牛蒡根", "食物", "", 0.1f, 150),
    new ItemEntry("GEAR_AcornCoffeeTin", "橡子咖啡罐", "饮料", "", 0.5f),
    new ItemEntry("GEAR_CookedPtarmiganWhole", "烤整只松鸡", "食物", "", 0.5f, 700),
    new ItemEntry("GEAR_RawPtarmiganWhole", "生整只松鸡", "食物", "", 0.6f),
    new ItemEntry("GEAR_CookedMeatCaribou", "熟驯鹿肉", "食物", "", 0.5f, 450),
    new ItemEntry("GEAR_RawMeatCaribou", "生驯鹿肉", "食物", "", 0.5f),
    new ItemEntry("GEAR_CookedCatTailStalk", "熟香蒲茎", "食物", "", 0.1f, 100),
    new ItemEntry("GEAR_CatTailStalk", "香蒲的茎干", "食物", "", 0.1f, 50),
    new ItemEntry("GEAR_MilkPowder", "奶粉", "食物", "", 0.3f, 300),
    new ItemEntry("GEAR_MilletFlour", "小米粉", "食物", "", 0.3f, 200),
    new ItemEntry("GEAR_WheatFlour", "面粉", "食物", "", 0.3f, 150),
    new ItemEntry("GEAR_OatmealPacket", "燕麦包", "食物", "", 0.1f, 300),
    new ItemEntry("GEAR_BirchbarkTeaDried", "桦树皮(晒干)", "材料", "", 0.05f),
    new ItemEntry("GEAR_Bow", "生存的弓", "武器", "", 1f),
    new ItemEntry("GEAR_BowB", "猎弓B", "武器", "", 1f),
    new ItemEntry("GEAR_BowC", "猎弓C", "武器", "", 1f),
    new ItemEntry("GEAR_FlareGun", "信号枪", "武器", "", 1f),
    new ItemEntry("GEAR_Rifle", "步枪", "武器", "", 4f),
    new ItemEntry("GEAR_RifleB", "山地步枪", "武器", "", 4f),
    new ItemEntry("GEAR_RifleC", "步枪C", "武器", "", 4f),
    new ItemEntry("GEAR_Revolver", "左轮手枪", "武器", "", 1.5f),
    new ItemEntry("GEAR_RevolverB", "左轮手枪B", "武器", "", 1.5f),
    new ItemEntry("GEAR_Stone", "石块", "武器", "", 0.5f),
    new ItemEntry("GEAR_Shotgun", "霰弹枪", "武器", "", 3.5f, 0, "Tales DLC 第5章武器"),
    new ItemEntry("GEAR_Arrow", "简单的箭", "武器", "", 0.1f),
    new ItemEntry("GEAR_ArrowHardened", "淬火箭", "武器", "", 0.1f),
    new ItemEntry("GEAR_ArrowHead", "箭头", "武器", "", 0.05f),
    new ItemEntry("GEAR_ArrowShaft", "箭杆", "武器", "", 0.05f),
    new ItemEntry("GEAR_BlueFlare", "海军陆战队信号弹", "武器", "", 0.2f),
    new ItemEntry("GEAR_BrokenArrow", "断箭", "武器", "", 0.08f),
    new ItemEntry("GEAR_BrokenArrowHardened", "破损淬火箭", "武器", "", 0.08f),
    new ItemEntry("GEAR_Bullet", "弹头", "武器", "", 0.05f),
    new ItemEntry("GEAR_FlareA", "信号棒", "武器", "", 0.2f),
    new ItemEntry("GEAR_FlareGunAmmoSingle", "信号弹", "武器", "", 0.1f),
    new ItemEntry("GEAR_RevolverAmmoBox", "左轮弹药箱", "武器", "", 0.15f),
    new ItemEntry("GEAR_RevolverAmmoCasing", "左轮弹壳", "武器", "", 0.02f),
    new ItemEntry("GEAR_RevolverAmmoSingle", "左轮子弹(单发)", "武器", "", 0.03f),
    new ItemEntry("GEAR_RifleAmmoBox", "步枪弹药箱", "武器", "", 0.2f),
    new ItemEntry("GEAR_RifleAmmoCasing", "步枪弹壳", "武器", "", 0.02f),
    new ItemEntry("GEAR_RifleAmmoSingle", "步枪子弹(单发)", "武器", "", 0.05f),
    new ItemEntry("GEAR_ScrapLead", "废铅", "武器", "", 0.1f),
    new ItemEntry("GEAR_SprayPaintCan", "喷漆罐", "武器", "", 0.3f),
    new ItemEntry("GEAR_SprayPaintCanGlyphA", "符文喷漆罐", "武器", "", 0.3f),
    new ItemEntry("GEAR_ShotgunAmmoSingleBirdshot", "霰弹枪子弹-鸟弹(单发)", "武器", "", 0.05f),
    new ItemEntry("GEAR_ShotgunAmmoSingleBuckshot", "霰弹枪子弹-鹿弹(单发)", "武器", "", 0.05f),
    new ItemEntry("GEAR_ShotgunAmmoSingleSlug", "霰弹枪子弹-独弹(单发)", "武器", "", 0.05f),
    new ItemEntry("GEAR_ShotgunAmmoBoxBirdshot", "霰弹枪弹药箱-鸟弹", "武器", "", 0.25f),
    new ItemEntry("GEAR_ShotgunAmmoBoxBuckshot", "霰弹枪弹药箱-鹿弹", "武器", "", 0.25f),
    new ItemEntry("GEAR_ShotgunAmmoBoxSlug", "霰弹枪弹药箱-独弹", "武器", "", 0.25f),
    new ItemEntry("GEAR_ShotgunAmmoCasing", "霰弹枪弹壳", "武器", "", 0.02f),
    new ItemEntry("GEAR_SpearFishingHead", "鱼叉头", "武器", "", 0.1f),
    new ItemEntry("GEAR_BottleAntibiotics", "抗生素", "医疗", "", 0.1f),
    new ItemEntry("GEAR_BottleHydrogenPeroxide", "消毒剂", "医疗", "", 0.2f),
    new ItemEntry("GEAR_BottlePainKillers", "止痛药", "医疗", "", 0.1f),
    new ItemEntry("GEAR_HeavyBandage", "重型绷带", "医疗", "", 0.2f),
    new ItemEntry("GEAR_Bandage", "绷带", "医疗", "", 0.1f),
    new ItemEntry("GEAR_BottleOfWater", "急救水", "医疗", "", 0.5f),
    new ItemEntry("GEAR_AntiInfectionWipes", "消毒湿巾", "医疗", "", 0.05f),
    new ItemEntry("GEAR_StitchingKit", "缝合套件", "医疗", "", 0.1f),
    new ItemEntry("GEAR_EmergencyStim", "强心针", "医疗", "", 0.05f),
    new ItemEntry("GEAR_BoltCutters", "螺栓割刀", "工具", "", 1.5f),
    new ItemEntry("GEAR_CanOpener", "开罐器", "工具", "", 0.1f),
    new ItemEntry("GEAR_CookingPot", "锅子", "工具", "", 1f),
    new ItemEntry("GEAR_Firestriker", "打火器", "工具", "", 0.1f),
    new ItemEntry("GEAR_Flashlight", "手电", "工具", "", 0.5f),
    new ItemEntry("GEAR_Flashlight_LongLasting", "矿工用手电", "工具", "", 0.6f, 0, "Tales DLC,长寿命"),
    new ItemEntry("GEAR_FishingLureA", "鱼饵A", "工具", "", 0.02f),
    new ItemEntry("GEAR_FishingLureB", "鱼饵B", "工具", "", 0.02f),
    new ItemEntry("GEAR_FishingLureC", "鱼饵C", "工具", "", 0.02f),
    new ItemEntry("GEAR_Hacksaw", "钢锯", "工具", "", 0.8f),
    new ItemEntry("GEAR_Hammer", "重锤", "工具", "", 1f),
    new ItemEntry("GEAR_Hatchet", "小斧头", "工具", "", 1.5f),
    new ItemEntry("GEAR_HatchetImprovised", "简易小斧", "工具", "", 1.2f),
    new ItemEntry("GEAR_HighQualityTools", "高质工具", "工具", "", 2f),
    new ItemEntry("GEAR_Hook", "钩子", "工具", "", 0.01f),
    new ItemEntry("GEAR_HookAndLine", "钩线组合", "工具", "", 0.05f),
    new ItemEntry("GEAR_ImprovisedCrampons", "简易鞋底钉", "工具", "", 0.5f),
    new ItemEntry("GEAR_JeremiahKnife", "杰里迈亚的刀", "工具", "", 0.3f),
    new ItemEntry("GEAR_Knife", "猎刀", "工具", "", 0.3f),
    new ItemEntry("GEAR_KnifeImprovised", "简易小刀", "工具", "", 0.3f),
    new ItemEntry("GEAR_KnifeScrapMetal", "废金属刀", "工具", "", 0.3f),
    new ItemEntry("GEAR_Line", "鱼线", "工具", "", 0.05f),
    new ItemEntry("GEAR_MagnifyingLens", "放大镜", "工具", "", 0.1f),
    new ItemEntry("GEAR_NoiseMaker", "制噪器", "工具", "", 0.3f),
    new ItemEntry("GEAR_PackMatches", "盒装火柴", "工具", "", 0.05f),
    new ItemEntry("GEAR_Prybar", "撬棍", "工具", "", 1f),
    new ItemEntry("GEAR_RifleCleaningKit", "枪械清理套件", "工具", "", 0.5f),
    new ItemEntry("GEAR_SewingKit", "针线包", "工具", "", 0.1f),
    new ItemEntry("GEAR_SharpeningStone", "磨刀石", "工具", "", 0.2f),
    new ItemEntry("GEAR_SimpleTools", "简易工具箱", "工具", "", 1f),
    new ItemEntry("GEAR_Snare", "陷阱", "工具", "", 0.3f),
    new ItemEntry("GEAR_TipUp", "上钩指示器", "工具", "", 0.5f),
    new ItemEntry("GEAR_CarBattery", "蓄电池", "工具", "", 5f),
    new ItemEntry("GEAR_Torch", "火把", "工具", "", 0.5f),
    new ItemEntry("GEAR_Vice", "工作台老虎钳", "工具", "", 5f),
    new ItemEntry("GEAR_WoodMatches", "木制火柴", "工具", "", 0.05f),
    new ItemEntry("GEAR_WoodworkingTools", "木工工具", "工具", "", 2f),
    new ItemEntry("GEAR_KeroseneLampB", "煤油灯", "工具", "", 0.5f),
    new ItemEntry("GEAR_KeroseneLamp_Spelunkers", "探洞者提灯", "工具", "", 0.5f),
    new ItemEntry("GEAR_Compass", "指南针", "工具", "", 0.1f),
    new ItemEntry("GEAR_FishingTackleBox", "钓具箱", "工具", "", 0.3f),
    new ItemEntry("GEAR_SpearFishing", "鱼叉", "工具", "", 1.5f),
    new ItemEntry("GEAR_RevolverCleaningKit", "左轮清洁套件", "工具", "", 0.3f),
    new ItemEntry("GEAR_SafeCrackingStethoscope", "听诊器(开保险箱)", "工具", "", 0.1f),
    new ItemEntry("GEAR_Balaclava", "巴拉克拉法帽", "衣物", "", 0.2f),
    new ItemEntry("GEAR_BaseballCap", "棒球帽", "衣物", "", 0.1f),
    new ItemEntry("GEAR_BasicBoots", "基本靴子", "衣物", "", 1f),
    new ItemEntry("GEAR_BasicGloves", "基本手套", "衣物", "", 0.2f),
    new ItemEntry("GEAR_BasicShoes", "基础鞋", "衣物", "", 0.5f),
    new ItemEntry("GEAR_BasicWinterCoat", "基本冬季大衣", "衣物", "", 1.5f),
    new ItemEntry("GEAR_BasicWoolHat", "棉布无檐毛线帽", "衣物", "", 0.1f),
    new ItemEntry("GEAR_BasicWoolScarf", "羊毛围巾", "衣物", "", 0.1f),
    new ItemEntry("GEAR_BearSkinCoat", "熊皮大衣", "衣物", "", 5f),
    new ItemEntry("GEAR_CargoPants", "工装裤", "衣物", "", 0.8f),
    new ItemEntry("GEAR_ClimbingSocks", "登山袜", "衣物", "", 0.1f),
    new ItemEntry("GEAR_CombatBoots", "军靴", "衣物", "", 1.5f),
    new ItemEntry("GEAR_CombatPants", "作战裤", "衣物", "", 1f),
    new ItemEntry("GEAR_CottonHoodie", "连帽衫", "衣物", "", 0.5f),
    new ItemEntry("GEAR_CottonScarf", "棉布围巾", "衣物", "", 0.1f),
    new ItemEntry("GEAR_CottonShirt", "礼服衬衫", "衣物", "", 0.3f),
    new ItemEntry("GEAR_DeerSkinBoots", "鹿皮靴", "衣物", "", 1f),
    new ItemEntry("GEAR_DeerSkinPants", "鹿皮短裤", "衣物", "", 1.5f),
    new ItemEntry("GEAR_DownVest", "羽绒背心", "衣物", "", 0.5f),
    new ItemEntry("GEAR_EarMuffs", "羊毛耳套", "衣物", "", 0.2f),
    new ItemEntry("GEAR_FleeceMittens", "羊绒连指手套", "衣物", "", 0.2f),
    new ItemEntry("GEAR_FleeceSweater", "羊绒毛衣", "衣物", "", 0.5f),
    new ItemEntry("GEAR_Gauntlets", "长手套", "衣物", "", 0.5f),
    new ItemEntry("GEAR_HeavyWoolSweater", "厚羊毛衫", "衣物", "", 1f),
    new ItemEntry("GEAR_ImprovisedHat", "简易头巾", "衣物", "", 0.3f),
    new ItemEntry("GEAR_ImprovisedMittens", "简易扎手带", "衣物", "", 0.3f),
    new ItemEntry("GEAR_InsulatedPants", "雪花裤", "衣物", "", 1f),
    new ItemEntry("GEAR_InsulatedVest", "防水马甲", "衣物", "", 0.8f),
    new ItemEntry("GEAR_Jeans", "牛仔裤", "衣物", "", 0.7f),
    new ItemEntry("GEAR_LeatherShoes", "皮鞋", "衣物", "", 0.8f),
    new ItemEntry("GEAR_LightParka", "简易风雪大衣", "衣物", "", 1.5f),
    new ItemEntry("GEAR_LongUnderwear", "长内衣", "衣物", "", 0.4f),
    new ItemEntry("GEAR_LongUnderwearWool", "羊毛长内衣", "衣物", "", 0.5f),
    new ItemEntry("GEAR_Mittens", "连指手套", "衣物", "", 0.2f),
    new ItemEntry("GEAR_MooseHideBag", "驼鹿皮背包", "衣物", "", 1f),
    new ItemEntry("GEAR_MooseHideCloak", "驼鹿皮斗篷", "衣物", "", 4f),
    new ItemEntry("GEAR_PlaidShirt", "格子花呢上衣", "衣物", "", 0.4f),
    new ItemEntry("GEAR_RabbitSkinMittens", "兔皮连指手套", "衣物", "", 0.3f),
    new ItemEntry("GEAR_RabbitskinHat", "兔皮帽", "衣物", "", 0.3f),
    new ItemEntry("GEAR_SkiGloves", "滑雪手套", "衣物", "", 0.3f),
    new ItemEntry("GEAR_SkiJacket", "滑雪衫", "衣物", "", 1.5f),
    new ItemEntry("GEAR_TeeShirt", "T 恤衫", "衣物", "", 0.2f),
    new ItemEntry("GEAR_Toque", "羊毛无檐毛线帽", "衣物", "", 0.1f),
    new ItemEntry("GEAR_WolfSkinCape", "狼皮大衣", "衣物", "", 3f),
    new ItemEntry("GEAR_WorkBoots", "工作靴", "衣物", "", 1.5f),
    new ItemEntry("GEAR_WorkGloves", "工作手套", "衣物", "", 0.2f),
    new ItemEntry("GEAR_WorkPants", "工作裤", "衣物", "", 0.8f),
    new ItemEntry("GEAR_WoolSocks", "羊毛短袜", "衣物", "", 0.1f),
    new ItemEntry("GEAR_WoolSweater", "羊毛毛衣", "衣物", "", 0.8f),
    new ItemEntry("GEAR_WoolWrap", "长款羊毛围巾", "衣物", "", 0.2f),
    new ItemEntry("GEAR_WoolWrapCap", "绒面蒙头斗篷", "衣物", "", 0.2f),
    new ItemEntry("GEAR_ArmWrap", "手臂绑带", "衣物", "", 0.1f),
    new ItemEntry("GEAR_LeatherBindings", "皮革绑腿", "衣物", "", 0.2f),
    new ItemEntry("GEAR_MackinawJacket", "麦基诺厚呢夹克", "衣物", "", 1.5f),
    new ItemEntry("GEAR_PrisonerVest", "囚犯背心", "衣物", "", 0.3f),
    new ItemEntry("GEAR_SurvivorParka", "幸存者派克大衣", "衣物", "", 2f),
    new ItemEntry("GEAR_WolfskinParka", "狼皮派克大衣", "衣物", "", 2.5f),
    new ItemEntry("GEAR_ColdFusionSuit", "极寒防护套装", "衣物", "", 3f),
    new ItemEntry("GEAR_HeavyParka", "老式风雪大衣", "衣物", "", 2.5f),
    new ItemEntry("GEAR_TacticalGloves", "战术手套", "衣物", "", 0.3f),
    new ItemEntry("GEAR_TacticalJacket", "战术夹克", "衣物", "", 2f),
    new ItemEntry("GEAR_ExpeditionCoat", "远征风雪大衣", "衣物", "", 2.5f),
    new ItemEntry("GEAR_ExpeditionParka", "远征派克大衣", "衣物", "", 2.5f),
    new ItemEntry("GEAR_Accelerant", "助燃剂", "材料", "", 0.1f),
    new ItemEntry("GEAR_AccelerantGunpowder", "火药引火剂", "材料", "", 0.1f),
    new ItemEntry("GEAR_AccelerantKerosene", "煤油引火剂", "材料", "", 0.1f),
    new ItemEntry("GEAR_BarkTinder", "桦树皮", "材料", "", 0.05f),
    new ItemEntry("GEAR_BearHide", "新剥取的黑熊毛皮", "狩猎", "", 5f),
    new ItemEntry("GEAR_BearHideDried", "鞣制的黑熊毛皮", "狩猎", "", 3f),
    new ItemEntry("GEAR_BearQuarter", "小块熊尸", "狩猎", "", 4f),
    new ItemEntry("GEAR_BearSkinBedRoll", "熊皮睡袋", "工具", "", 2.5f),
    new ItemEntry("GEAR_BirchSaplingDried", "加工桦树苗", "材料", "", 0.2f),
    new ItemEntry("GEAR_BirchbarkPrepared", "加工过的桦树皮", "材料", "", 0.1f),
    new ItemEntry("GEAR_Charcoal", "木炭", "材料", "", 0.02f),
    new ItemEntry("GEAR_Coal", "煤炭", "材料", "", 1f),
    new ItemEntry("GEAR_Cloth", "布料", "材料", "", 0.1f),
    new ItemEntry("GEAR_CrowFeather", "乌鸦羽毛", "狩猎", "", 0.01f),
    new ItemEntry("GEAR_PtarmiganFeathers", "羽毛", "狩猎", "", 0.01f),
    new ItemEntry("GEAR_DustingSulfur", "硫粉", "材料", "", 0.1f),
    new ItemEntry("GEAR_Firelog", "加工木柴", "材料", "", 1.5f),
    new ItemEntry("GEAR_GunpowderCan", "火药罐", "材料", "", 0.3f),
    new ItemEntry("GEAR_Gut", "新鲜内脏", "狩猎", "", 0.1f),
    new ItemEntry("GEAR_GutDried", "加工内脏", "狩猎", "", 0.05f),
    new ItemEntry("GEAR_Hardwood", "硬木", "材料", "", 1f),
    new ItemEntry("GEAR_LampFuel", "灯油", "材料", "", 0.5f),
    new ItemEntry("GEAR_LeatherDried", "鞣制的皮革", "狩猎", "", 0.3f),
    new ItemEntry("GEAR_LeatherHide", "皮革(生)", "狩猎", "", 0.5f),
    new ItemEntry("GEAR_LeatherHideDried", "皮革毛皮(晒干)", "狩猎", "", 0.3f),
    new ItemEntry("GEAR_MapleSaplingDried", "加工枫树苗", "材料", "", 0.2f),
    new ItemEntry("GEAR_MooseHideDried", "鞣制的驼鹿皮", "狩猎", "", 2f),
    new ItemEntry("GEAR_Newsprint", "报纸", "材料", "", 0.05f),
    new ItemEntry("GEAR_NewsprintRoll", "一卷报纸", "材料", "", 0.1f),
    new ItemEntry("GEAR_PaperStack", "纸堆", "材料", "", 0.2f),
    new ItemEntry("GEAR_RabbitCarcass", "兔子尸体", "狩猎", "", 0.5f),
    new ItemEntry("GEAR_RabbitPelt", "兔皮(生)", "狩猎", "", 0.3f),
    new ItemEntry("GEAR_RabbitPeltDried", "兔皮(晒干)", "狩猎", "", 0.15f),
    new ItemEntry("GEAR_ReclaimedWoodB", "回收木材", "材料", "", 0.5f),
    new ItemEntry("GEAR_RecycledCan", "回收的空罐", "材料", "", 0.1f),
    new ItemEntry("GEAR_ScrapMetal", "废金属", "材料", "", 0.5f),
    new ItemEntry("GEAR_Softwood", "软木", "材料", "", 0.5f),
    new ItemEntry("GEAR_SpearHead", "矛尖", "材料", "", 0.3f),
    new ItemEntry("GEAR_StagQuarter", "小块鹿尸", "狩猎", "", 4f),
    new ItemEntry("GEAR_Stick", "树枝", "材料", "", 0.1f),
    new ItemEntry("GEAR_StumpRemover", "树桩去除剂", "材料", "", 0.3f),
    new ItemEntry("GEAR_Tinder", "火绒", "材料", "", 0.05f),
    new ItemEntry("GEAR_WolfCarcass", "狼的尸骸", "狩猎", "", 8f),
    new ItemEntry("GEAR_WolfPelt", "新剥取的狼皮", "狩猎", "", 2f),
    new ItemEntry("GEAR_WolfPeltDried", "鞣制的狼皮", "狩猎", "", 1f),
    new ItemEntry("GEAR_WolfQuarter", "小块狼尸", "狩猎", "", 3f),
    new ItemEntry("GEAR_Potato", "土豆", "食物", "", 0.2f, 50),
    new ItemEntry("GEAR_BoneB", "骨头", "狩猎", "", 0.2f),
    new ItemEntry("GEAR_BoneBearB", "熊骨头", "狩猎", "", 0.5f),
    new ItemEntry("GEAR_BoneDeerB", "鹿骨头", "狩猎", "", 0.3f),
    new ItemEntry("GEAR_BoneWolfB", "狼骨头", "狩猎", "", 0.3f),
    new ItemEntry("GEAR_BoneMooseB", "驼鹿骨头", "狩猎", "", 0.5f),
    new ItemEntry("GEAR_MooseQuarter", "驼鹿尸块", "狩猎", "", 4f),
    new ItemEntry("GEAR_PtarmiganCarcass", "松鸡尸骸", "狩猎", "", 0.5f),
    new ItemEntry("GEAR_PtarmiganPelt", "松鸡皮", "狩猎", "", 0.1f),
    new ItemEntry("GEAR_CaribouHide", "驯鹿皮(生)", "狩猎", "", 2f),
    new ItemEntry("GEAR_CaribouHideDried", "驯鹿皮(晒干)", "狩猎", "", 1.5f),
    new ItemEntry("GEAR_CougarHide", "新剥取的美洲狮皮", "狩猎", "", 3f),
    new ItemEntry("GEAR_CougarHideDried", "鞣制的美洲狮皮", "狩猎", "", 2f),
    new ItemEntry("GEAR_CougarClaw", "美洲狮爪", "狩猎", "", 0.05f, 0, "合成美洲狮爪刀"),
    new ItemEntry("GEAR_CuredLeather", "鞣制皮革", "狩猎", "", 0.3f),
    new ItemEntry("GEAR_ForgedKnifeBladeA", "锻造刀刃A", "材料", "", 0.3f),
    new ItemEntry("GEAR_ForgedKnifeBladeB", "锻造刀刃B", "材料", "", 0.3f),
    new ItemEntry("GEAR_ForgedHatchetHead", "锻造斧头", "材料", "", 0.5f),
    new ItemEntry("GEAR_SurvivalBow", "生存弓", "武器", "", 1f),
    new ItemEntry("GEAR_WolfCarcassMoose", "驼鹿皮革碎片", "狩猎", "", 1f),
    new ItemEntry("GEAR_OldWoolScarf", "旧羊毛围巾", "材料", "", 0.1f),
    new ItemEntry("GEAR_Rifle_barbs", "巴尔布的步枪", "武器", "", 4f, 0, "沿海公路，略重"),
    new ItemEntry("GEAR_Rifle_Vaughns", "沃恩的步枪", "武器", "", 4f, 0, "神秘湖，极轻"),
    new ItemEntry("GEAR_Rifle_curators", "管理人的步枪", "武器", "", 4f, 0, "灰烬峡谷，金饰"),
    new ItemEntry("GEAR_Rifle_Trader", "地堡步枪", "武器", "", 4f, 0, "Tales DLC 商人地堡专属"),
    new ItemEntry("GEAR_RifleBroken", "损毁的猎枪", "武器", "", 3f),
    new ItemEntry("GEAR_Bow_Manufactured", "运动弓", "武器", "", 1f, 0, "废弃机场，最轻"),
    new ItemEntry("GEAR_Bow_Woodwrights", "木匠的弓", "武器", "", 1f, 0, "寂静河谷，最重最稳"),
    new ItemEntry("GEAR_Bow_Bushcraft", "丛林生存弓", "武器", "", 1f),
    new ItemEntry("GEAR_RevolverFancy", "猎人的左轮手枪", "武器", "", 1.5f, 0, "远程伤害更高"),
    new ItemEntry("GEAR_RevolverGreen", "护林人的左轮手枪", "武器", "", 1.5f, 0, "绿色涂装"),
    new ItemEntry("GEAR_RevolverStubNosed", "典狱长的左轮手枪", "武器", "", 1.5f, 0, "短管，近距离强"),
    new ItemEntry("GEAR_Knife_Hunter", "狩猎刀（传奇）", "武器", "", 0.3f, 0, "更快剥皮，高耐久"),
    new ItemEntry("GEAR_CougarClawKnife", "美洲狮爪刀", "武器", "", 0.3f, 0, "美洲狮爪 + 锻造刀刃合成"),
    new ItemEntry("GEAR_Hatchet_Crafted", "手斧（传奇）", "武器", "", 1f, 0, "锻造版，效率更高"),
    new ItemEntry("GEAR_BearSpear", "猎熊矛", "武器", "", 2.5f, 0, "剧情DLC专属，可击杀熊"),
    new ItemEntry("GEAR_BearSpearBroken", "损坏的猎熊矛", "武器", "", 2f),
    new ItemEntry("GEAR_BookA", "书 A", "装饰", "", 0.5f),
    new ItemEntry("GEAR_BookB", "书 B", "装饰", "", 0.5f),
    new ItemEntry("GEAR_BookBopen", "书 B(翻开)", "装饰", "", 0.5f),
    new ItemEntry("GEAR_BookC", "书 C", "装饰", "", 0.5f),
    new ItemEntry("GEAR_BookD", "书 D", "装饰", "", 0.5f),
    new ItemEntry("GEAR_BookE", "书 E", "装饰", "", 0.5f),
    new ItemEntry("GEAR_BookEopen", "书 E(翻开)", "装饰", "", 0.5f),
    new ItemEntry("GEAR_BookF", "书 F", "装饰", "", 0.5f),
    new ItemEntry("GEAR_BookFopen", "书 F(翻开)", "装饰", "", 0.5f),
    new ItemEntry("GEAR_BookG", "书 G", "装饰", "", 0.5f),
    new ItemEntry("GEAR_BookH", "书 H", "装饰", "", 0.5f),
    new ItemEntry("GEAR_BookHopen", "书 H(翻开)", "装饰", "", 0.5f),
    new ItemEntry("GEAR_BookI", "书 I", "装饰", "", 0.5f),
    new ItemEntry("GEAR_BookLabE_01", "实验室书籍01", "装饰", "", 0.5f),
    new ItemEntry("GEAR_BookLabE_02", "实验室书籍02", "装饰", "", 0.5f),
    new ItemEntry("GEAR_BookLabE_03", "实验室书籍03", "装饰", "", 0.5f),
    new ItemEntry("GEAR_BookLabE_Open_01", "实验室书籍(翻开)01", "装饰", "", 0.5f),
    new ItemEntry("GEAR_BookManual", "手册", "装饰", "", 0.5f),
    new ItemEntry("GEAR_BlackrockCodeNote", "手写的笔记", "装饰", "", 0.05f),
    new ItemEntry("GEAR_DarkwalkerDiary1", "笔记页", "装饰", "", 0.05f),
    new ItemEntry("GEAR_DarkwalkerDiary2", "笔记页", "装饰", "", 0.05f),
    new ItemEntry("GEAR_DarkwalkerDiary3", "笔记页", "装饰", "", 0.05f),
    new ItemEntry("GEAR_DarkwalkerDiary4", "笔记页", "装饰", "", 0.05f),
    new ItemEntry("GEAR_DarkwalkerDiary5", "笔记页", "装饰", "", 0.05f),
    new ItemEntry("GEAR_DarkwalkerDiary6", "笔记页", "装饰", "", 0.05f),
    new ItemEntry("GEAR_DarkwalkerDiary7", "笔记页", "装饰", "", 0.05f),
    new ItemEntry("GEAR_DarkwalkerDiary8", "笔记页", "装饰", "", 0.05f),
    new ItemEntry("GEAR_DarkwalkerDiary9", "笔记页", "装饰", "", 0.05f),
    new ItemEntry("GEAR_DarkwalkerDiary10", "笔记页", "装饰", "", 0.05f),
    new ItemEntry("GEAR_DeadmanNote1", "墓志铭 1", "装饰", "", 0.05f),
    new ItemEntry("GEAR_DeadmanNote2", "墓志铭 2", "装饰", "", 0.05f),
    new ItemEntry("GEAR_DeadmanNote3", "墓志铭 3", "装饰", "", 0.05f),
    new ItemEntry("GEAR_DeadmanNote4", "墓志铭 4", "装饰", "", 0.05f),
    new ItemEntry("GEAR_DeadmanNote5", "墓志铭 5", "装饰", "", 0.05f),
    new ItemEntry("GEAR_VisorNoteBlackrock2", "潦草的信息", "装饰", "", 0.05f),
    new ItemEntry("GEAR_VisorNoteCH1", "潦草的信息", "装饰", "", 0.05f),
    new ItemEntry("GEAR_VisorNoteCH2", "潦草的信息", "装饰", "", 0.05f),
    new ItemEntry("GEAR_VisorNoteFM1", "潦草的信息", "装饰", "", 0.05f),
    new ItemEntry("GEAR_VisorNoteFM2", "潦草的信息", "装饰", "", 0.05f),
    new ItemEntry("GEAR_VisorNoteHRV2", "潦草的信息", "装饰", "", 0.05f),
    new ItemEntry("GEAR_VisorNoteMT3", "潦草的信息", "装饰", "", 0.05f),
    new ItemEntry("GEAR_VisorNotePV1", "潦草的信息", "装饰", "", 0.05f),
    new ItemEntry("GEAR_VisorNotePV3", "潦草的信息", "装饰", "", 0.05f),
    new ItemEntry("GEAR_BedRoll", "睡袋", "工具", "", 1f),
    new ItemEntry("GEAR_Placeholder", "占位物品", "装饰", "", 0.1f),
    new ItemEntry("GEAR_ArrowManufactured", "精工箭", "武器", "", 0.5f),
    new ItemEntry("GEAR_ArrowManufacturedHead", "量产箭头", "武器", "", 0.5f),
    new ItemEntry("GEAR_ArrowManufacturedShaft", "量产箭杆", "武器", "", 0.5f),
    new ItemEntry("GEAR_BrokenArrowManufactured", "断掉的精工箭", "武器", "", 0.5f),
    new ItemEntry("GEAR_ArrowSurvival", "生存箭", "武器", "", 0.5f),
    new ItemEntry("GEAR_HuntingRifle", "猎枪", "武器", "", 0.5f),
    new ItemEntry("GEAR_Revolver44Mag", "44马格南左轮", "武器", "", 0.5f),
    new ItemEntry("GEAR_RevolverFlat", "平身左轮", "武器", "", 0.5f),
    new ItemEntry("GEAR_SurvivalKnife", "求生刀", "武器", "", 0.5f),
    new ItemEntry("GEAR_BookGunsmithing", "枪械学", "装饰", "", 0.5f),
    new ItemEntry("GEAR_BookRevolverFirearm", "轻武器手册", "装饰", "", 0.5f),
    new ItemEntry("GEAR_BookRifleFirearm", "《前沿射击指南》", "装饰", "", 0.5f),
    new ItemEntry("GEAR_BookRifleFirearmAdvanced", "《铳·枪·炮 - 高级射击》", "装饰", "", 0.5f),
    new ItemEntry("GEAR_BookArchery", "紧盯目标", "装饰", "", 0.5f),
    new ItemEntry("GEAR_BookCarcassHarvesting", "尸体处理", "装饰", "", 0.5f),
    new ItemEntry("GEAR_BookCooking", "《荒野厨房》", "装饰", "", 0.5f),
    new ItemEntry("GEAR_BookFireStarting", "《户外生存！》", "装饰", "", 0.5f),
    new ItemEntry("GEAR_BookIceFishing", "《冰上钓鱼人》", "装饰", "", 0.5f),
    new ItemEntry("GEAR_BookMending", "缝纫初级读本", "装饰", "", 0.5f),
    new ItemEntry("GEAR_AirlineFoodChick", "航空餐(鸡)", "食物", "", 0.5f),
    new ItemEntry("GEAR_AirlineFoodVeg", "航空餐(素)", "食物", "", 0.5f),
    new ItemEntry("GEAR_CannedBeansB", "罐装豆类B", "食物", "", 0.5f),
    new ItemEntry("GEAR_CannedPeasAndCarrots", "罐装豌豆胡萝卜", "食物", "", 0.5f),
    new ItemEntry("GEAR_Crackers", "饼干", "食物", "", 0.5f),
    new ItemEntry("GEAR_CuredMeatA", "腌肉", "食物", "", 0.5f),
    new ItemEntry("GEAR_DriedApples", "苹果干", "食物", "", 0.5f),
    new ItemEntry("GEAR_DriedMangos", "干芒果", "食物", "", 0.5f),
    new ItemEntry("GEAR_MeatFat", "动物脂肪", "食物", "", 0.5f),
    new ItemEntry("GEAR_MeatFat_Spoiled", "变质动物脂肪", "食物", "", 0.5f),
    new ItemEntry("GEAR_Pickled_Eggs", "腌蛋", "食物", "", 0.5f),
    new ItemEntry("GEAR_Pickled_Onions", "腌洋葱", "食物", "", 0.5f),
    new ItemEntry("GEAR_Pickles", "腌菜", "食物", "", 0.5f),
    new ItemEntry("GEAR_RawLakeBurbot", "生湖江鳕", "食物", "", 0.5f),
    new ItemEntry("GEAR_CaffeineBox", "咖啡因盒", "饮料", "", 0.5f),
    new ItemEntry("GEAR_WaterBottle", "水瓶", "饮料", "", 0.5f),
    new ItemEntry("GEAR_WaterBottleLabel", "水瓶标签", "装饰", "", 0.5f),
    new ItemEntry("GEAR_JerrycanRusty", "生锈油桶", "工具", "", 0.5f),
    new ItemEntry("GEAR_AntibioticPillBottle", "抗生素瓶", "医疗", "", 0.5f),
    new ItemEntry("GEAR_HeatPad", "热敷包", "医疗", "", 0.5f),
    new ItemEntry("GEAR_BallisticVest", "防弹背心", "衣物", "", 0.5f),
    new ItemEntry("GEAR_TechnicalBackpack", "高科技背包", "衣物", "", 0.5f),
    new ItemEntry("GEAR_InsulatedFlask_A", "保温瓶 A (1L)", "工具", "", 0.25f),
    new ItemEntry("GEAR_InsulatedFlask_B", "保温瓶 B (1.5L)", "工具", "", 0.25f),
    new ItemEntry("GEAR_InsulatedFlask_C", "保温瓶 C (2L)", "工具", "", 0.25f),
    new ItemEntry("GEAR_InsulatedFlask_D", "保温瓶 D (2.5L)", "工具", "", 0.25f),
    new ItemEntry("GEAR_InsulatedFlask_E", "保温瓶 E (3L)", "工具", "", 0.25f),
    new ItemEntry("GEAR_InsulatedFlask_F", "保温瓶 F (3.5L)", "工具", "", 0.25f),
    new ItemEntry("GEAR_InsulatedFlask_G", "保温瓶 G (4L)", "工具", "", 0.25f),
    new ItemEntry("GEAR_CowichanSweater", "印第安式厚毛衣", "衣物", "", 0.5f),
    new ItemEntry("GEAR_CottonSocks", "运动袜", "衣物", "", 0.5f),
    new ItemEntry("GEAR_DownParka", "城市风雪大衣", "衣物", "", 0.5f),
    new ItemEntry("GEAR_DownSkiJacket", "羽绒滑雪夹克", "衣物", "", 0.5f),
    new ItemEntry("GEAR_FishermanSweater", "渔夫毛衣", "衣物", "", 0.5f),
    new ItemEntry("GEAR_InsulatedBoots", "橡胶靴", "衣物", "", 0.5f),
    new ItemEntry("GEAR_MilitaryParka", "军用大衣", "衣物", "", 0.5f),
    new ItemEntry("GEAR_MuklukBoots", "皮制软靴", "衣物", "", 0.5f),
    new ItemEntry("GEAR_PremiumWinterCoat", "优质冬季大衣", "衣物", "", 0.5f),
    new ItemEntry("GEAR_QualityWinterCoat", "优质冬装", "衣物", "", 0.5f),
    new ItemEntry("GEAR_SkiBoots", "滑雪靴", "衣物", "", 0.5f),
    new ItemEntry("GEAR_SweaterChristmasA", "节日毛衣", "衣物", "", 0.5f),
    new ItemEntry("GEAR_WoolShirt", "羊毛衬衫", "衣物", "", 0.5f),
    new ItemEntry("GEAR_NewsprintBootStuffing", "报纸鞋衬", "衣物", "", 0.5f),
    new ItemEntry("GEAR_Deerskin_pants", "鹿皮裤(变体)", "衣物", "", 0.5f),
    new ItemEntry("GEAR_Crampons", "鞋底钉", "工具", "", 0.5f),
    new ItemEntry("GEAR_SurvivalElevatorCrank", "生存电梯曲柄", "工具", "", 0.5f),
    new ItemEntry("GEAR_Toolbox_Simple", "简易工具箱", "工具", "", 0.5f),
    new ItemEntry("GEAR_LampFuelFull", "满灯油", "工具", "", 0.5f),
    new ItemEntry("GEAR_TipUp_Flag", "冰钓旗", "工具", "", 0.5f),
    new ItemEntry("GEAR_FishingLine", "钓鱼线(整轴)", "工具", "", 0.5f),
    new ItemEntry("GEAR_FishingBaitA", "鱼饵", "工具", "", 0.5f),
    new ItemEntry("GEAR_RockCacheA", "石头堆", "工具", "", 0.5f),
    new ItemEntry("GEAR_Rope", "登山绳", "工具", "", 0.5f),
    new ItemEntry("GEAR_CattailPlant", "香蒲", "工具", "", 0.5f),
    new ItemEntry("GEAR_CattailStalk", "香蒲茎", "工具", "", 0.5f),
    new ItemEntry("GEAR_CattailTinder", "香蒲的顶穗", "工具", "", 0.5f),
    new ItemEntry("GEAR_BirchSapling", "绿色桦树苗", "材料", "", 0.5f),
    new ItemEntry("GEAR_MapleSapling", "绿色枫树苗", "材料", "", 0.5f),
    new ItemEntry("GEAR_NewsprintInsulation", "报纸保暖填充", "材料", "", 0.5f),
    new ItemEntry("GEAR_Leather", "新鲜皮革", "狩猎", "", 0.5f),
    new ItemEntry("GEAR_Leather_Dried_Shoes", "皮革鞋面(晒干)", "狩猎", "", 0.5f),
    new ItemEntry("GEAR_Leather_Shoes", "皮革鞋面", "狩猎", "", 0.5f),
    new ItemEntry("GEAR_MooseHide", "新剥取的驼鹿皮", "狩猎", "", 0.5f),
    new ItemEntry("GEAR_TimberwolfQuarter", "灰狼肉块", "狩猎", "", 0.5f),
    new ItemEntry("GEAR_AcornShelled_Bbig", "去壳橡子(大版)", "食物", "", 0.5f),
    new ItemEntry("GEAR_BedRoll_Blend", "睡袋(变体)", "工具", "", 0.5f),
    new ItemEntry("GEAR_CookingPotDummy", "炊具锅(占位)", "工具", "", 0.5f),
    new ItemEntry("GEAR_Flashlight_DIf", "手电筒(变体)", "工具", "", 0.5f),
    new ItemEntry("GEAR_LabelVitamins", "维生素标签", "装饰", "", 0.5f),
    new ItemEntry("GEAR_Film_Box_BW", "黑白胶卷盒", "装饰", "", 0.5f),
    new ItemEntry("GEAR_Film_Box_Colour", "彩色胶卷盒", "装饰", "", 0.5f),
    new ItemEntry("GEAR_Film_Box_Sepia", "棕褐胶卷盒", "装饰", "", 0.5f),
    new ItemEntry("GEAR_BlackrockAdminNote", "纸页", "装饰", "", 0.5f),
    new ItemEntry("GEAR_BlackrockAmmoRoomNote", "黑岩地区备忘录", "装饰", "", 0.5f),
    new ItemEntry("GEAR_BlackrockSecurityNote", "留言", "装饰", "", 0.5f),
    new ItemEntry("GEAR_BlackrockTowerNote", "留言", "装饰", "", 0.5f),
    new ItemEntry("GEAR_CanneryCodeNote", "通讯报告", "装饰", "", 0.5f),
    new ItemEntry("GEAR_CanneryMemo", "罐头厂备忘", "装饰", "", 0.5f),
    new ItemEntry("GEAR_CannerySurvivalPath", "技师的笔记本", "装饰", "", 0.5f),
    new ItemEntry("GEAR_CanyonClimbersCaveNote", "笔记本页", "装饰", "", 0.5f),
    new ItemEntry("GEAR_CanyonDeadClimberNote", "笔记本页", "装饰", "", 0.5f),
    new ItemEntry("GEAR_CanyonMinersNote", "开采日志页面", "装饰", "", 0.5f),
    new ItemEntry("GEAR_ClimbersJournal", "登山者的日志", "装饰", "", 0.5f),
    new ItemEntry("GEAR_BankManagerHouseKey", "银行经理家钥匙", "装饰", "", 0.5f),
    new ItemEntry("GEAR_Basement_Key_EP3", "地下室钥匙EP3", "装饰", "", 0.5f),
    new ItemEntry("GEAR_DepositBoxKey", "保险箱钥匙", "装饰", "", 0.5f),
    new ItemEntry("GEAR_MountainTownFarmKey", "山镇农场钥匙", "装饰", "", 0.5f),
    new ItemEntry("GEAR_MountainTownLockBoxKey", "山镇锁箱钥匙", "装饰", "", 0.5f),
    };

    // 分类顺序,作为 UI tab key 和 ItemEntry.Category 过滤 key,保持中文不变
    public static readonly string[] Categories = { "全部", "食物", "饮料", "工具", "武器", "医疗", "衣物", "狩猎", "材料", "装饰" };
    // UI 显示用,与 Categories 同序;靠 I18n 切换语言
    public static readonly string[] CategoriesEn = { "All", "Food", "Drinks", "Tools", "Weapons", "Medical", "Clothing", "Hunting", "Materials", "Decor" };
    public static string DisplayCategory(int i)
        => I18n.IsEnglish ? CategoriesEn[i] : Categories[i];
}
